### ISSUE TITLE
Docs Page is not rendering

### ISSUE THREAD

**Issue by mgcdanny** [bashtage/linearmodels#102]
The docs page is not rendering.  I am getting a 404:  https://bashtage.github.io/linearmodels/doc

**Comment by bashtage** [comment]
Thanks for pointing this out.  Dev docs are up at:

https://bashtage.github.io/linearmodels/devel/index.html

I'll try to get the main rebuilt.

**Comment by bashtage** [comment]
It is back now.   Thanks.
