### ISSUE TITLE
Syntax error in linearmodels/asset_pricing/model.py

### ISSUE THREAD

**Issue by rupaljaincc** [bashtage/linearmodels#137]
Hi,

I am getting following error while trying to use linearmodels.

File "anaconda/lib/python2.7/site-packages/linearmodels/asset_pricing/model.py", line 119
    def from_formula(cls, formula, data, *, portfolios=None):
                                          ^
SyntaxError: invalid syntax

**Comment by bashtage** [comment]
linearmodels is not compatible with Python 2 or any Python < 3.5.  It uses the `@` operator which was introduced in 3.5 in hundreds of places.

**Comment by bashtage** [comment]
It also uses keyword only arguments (the `', *, portfolios...`) bit, which is also from modern Python.
