### ISSUE TITLE
IVLIML: kappa with no exog

### ISSUE THREAD

**Issue by walkerdray** [bashtage/linearmodels#147]
If IVLIML is fit with no exogenous data, the eigenvalue 'kappa' is always set to 1 (ie, reduces to 2SLS). This looks to be done on purpose right now, but LIML can still be estimated with no exogenous data. Of course typically a constant is included, but in cases where one explicitly does not want a constant it would be nice to still be able to estimate LIML.

Is there a reason the LIML kappa estimation is set up this way? If not, seems like you could just get rid of the check for no exogenous regressors in the _estimate_kappa function and keep everything else as is.

**Comment by bashtage** [comment]
Thanks for raising this.  It has been fixed in master and will be broadly available in the next release.
