### ISSUE TITLE
PanelOLS.from_formula performance issues

### ISSUE THREAD

**Issue by spillz** [bashtage/linearmodels#152]
Getting some unexpected performance issues when I use `PanelOLS.from_formula` on a dataframe that has lots of variables.  Problems are exacerbated if there are non-numeric types in the dataframe (even if unused). Notice if I do the patsy calls manually, performance is much better (including the timing of the patsy call).

```python
import pandas as pd, numpy as np, time, patsy
from linearmodels import PanelOLS
cols = [s+(str(x) if x>0 else '') for s in list('ABCD') for x in range(100)]
n = 1000
t= 50
df = pd.DataFrame(np.random.uniform(1.0,100.0,size=(n*t, len(cols))), columns=cols)
df.index = pd.MultiIndex.from_arrays(np.mgrid[0:n,0:t].reshape(2,n*t),names=['ID','YEAR'])
df['Y'] = df['A']+df['B']+df['C']+df['D']
df['A1'] = 'str'
df['D99'] = 'str'

# Run 1 - from_formula on full dataframe
t=time.time()
f1 = PanelOLS.from_formula('Y~A+C+D+EntityEffects', df).fit()
print('from_formula with strings in dataframe',time.time()-t)

#Run 2 - Call patsy manually on full dataframe
t=time.time()
e,x = patsy.dmatrices('Y~A+C+D',df,return_type='dataframe')
f2=PanelOLS(e, x, entity_effects=True).fit()
print('PanelOLS with strings in dataframe',time.time()-t)

#Run 3 - Drop the unused strings from the dataframe. Helps a bit but still slower than run #2.
del df['A1']
del df['D99']
t=time.time()
f3 = PanelOLS.from_formula('Y~A+C+D+EntityEffects', df).fit()
print('from_formula without strings in dataframe',time.time()-t)

print(f1)
print(f2)
print(f3)
```

Here's the first three lines of output showing the timings:

```
from_formula with strings in dataframe 1.1370854377746582
PanelOLS with strings in dataframe 0.09599709510803223
from_formula without strings in dataframe 0.5590300559997559
```

**Comment by bashtage** [comment]
The slowdown between 1 and 3 is due to the string begin coded as a categorical before calling patsy. The general from_formula slowdown is due to extra call to PanelData as a safety check that the input (which could be a DataFrame, a Panel, a ndarray or an xarray) can be turned into a DataFrame that patsy can use.

**Comment by spillz** [comment]
But that's a lot of slowdown and with my real data I'm getting 6s per model run instead of 0.15s per model run. I'm trying to incorporate into an automatic model selection program using patsy style formulas. I guess I will just have to do this manually. 

A separate but partly related issue is that `PanelOLS` renames the index levels, so using `predict` spits out output that isn't index-compatible with the original `DataFrame`. Is this necessary in the case of a `DataFrame`?

**Comment by bashtage** [comment]
There are some places where things can be optimized, for example it is doing a concat even when there are no categoricals.  This can be avoided (0.25s or so).  It is possible I can avoid the copy as well at this point since Patsy is safe. This will shave another 0.25s.  

I've mostly erred on the side of caution when setting up data to avoid overwriting user data.

**Comment by bashtage** [comment]
>>> A separate but partly related issue is that PanelOLS renames the index levels, so using predict spits out output that isn't index-compatible with the original DataFrame. Is this necessary in the case of a DataFrame?

Could you show a simple example?  Sounds unnecessary.

**Comment by spillz** [comment]
Just append

```python
print(f1.predict(data=df))
```

to the code above

**Comment by bashtage** [comment]
I just merged a small patch.  I think performance on master should be similar with from_formulas with a large df now, even with strings.

**Comment by bashtage** [comment]
I think I've resolved both of these.  Please reopen if they are still a problem.
