### ISSUE TITLE
Linearmodels 4.5 PanleOLS and PooledOLS prediction issue

### ISSUE THREAD

**Issue by miladmahdavilayen** [bashtage/linearmodels#163]
Hello everyone,
Could anyone please help me with this issue I have regarding to the prediction of the PanelOLS model I am using (in python) for this sample data. The error is caused from the source code I suppose. I've attached the codes I used and the error I keep getting below.
Thanks in advance for any helps.
Milad.

----beginning of the code:
import matplotlib.pyplot as plt
import numpy as np
from statsmodels.datasets import grunfeld
data = grunfeld.load_pandas().data
data.year = data.year.astype(np.int64)
# MultiIndex, entity - time
data = data.set_index(['firm','year'])
from linearmodels import PanelOLS
mod = mod = PanelOLS.from_formula('invest ~ 1 + value + capital +EntityEffects', data)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)
predicted = mod.predict(['value','capital'],data = data[:50] , exog = None)
print(predicted)
#plt.scatter(data.invest,predicted.fitted_values)
--- end

---Error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-fae21d15632d> in <module>()
----> 1 predicted = mod.predict(['value','capital'],data = data[:50] , exog = None)
      2 print(predicted)
      3 #plt.scatter(data.invest,predicted.fitted_values)
      4 #plt.scatter

C:\ProgramData\Anaconda3\lib\site-packages\linearmodels\panel\model.py in predict(self, params, exog, data, eval_env)
    683         if params.shape[0] == 1:
    684             params = params.T
--> 685         pred = pd.DataFrame(x @ params, index=exog.index, columns=['predictions'])
    686 
    687         return pred

TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'
---- End

**Comment by bashtage** [comment]
```
predicted = mod.predict(['value','capital'],data = data[:50] , exog = None)
```

should be 

```
predicted = mod.predict(res.params, data = data[:50] , exog = None)
```

`predict` takes parameters as the first argument.

**Comment by miladmahdavilayen** [comment]
Thank you so much. It was a great help.
