### ISSUE TITLE
FamaMacBeth Std. Errors / T-Stats

### ISSUE THREAD

**Issue by matbuechner** [bashtage/linearmodels#168]
I have encountered an issue pertaining to the computation of standard errors and measures dependent on them such as t-stats and p-values in the FamaMacBeth function. On some occasions the function will produce a parameter estimate, but no error statistics. More specifically, I receive a runtime warning of the following sort:

`..../linearmodels/panel/results.py:70: RuntimeWarning: invalid value encountered in sqrt`

Any suggestions are very welcome :)

**Comment by bashtage** [comment]
Can you produce an example using simulated data that makes this happen?  A small self-contained example makes it much easier to understand what is specifically happening.

If not, could you describe the size of the data you are using, and provide the function call the produces issues?  Are you rolling through the data and it occasionally occurs when rolling?

Broadly something in the covariance matrix estimation is not positive definite.  This is producing nan values which then propagate.

**Comment by matbuechner** [comment]
Unfortunately, I have not been able to produce the error with simulated data. Thus, to create a minimal example, I have disguised my data and made it accessible via this dropbox link: 

[https://www.dropbox.com/s/d7apc41c0pc86x3/FM_MinExampleData.pkl?dl=0](url)

The data consists of roughly 30,000 observations, 700 entities and 50 times. The underlying panel is unbalanced. The function call is static, i.e. non-rolling.

The function call is as follows: 

```python
import pandas as pd
import statsmodels.api as sm
from linearmodels import FamaMacBeth

#Load Sample
temp = pd.read_pickle('FM_MinExampleData.pkl')
temp.set_index(['Entity','Time'],inplace=True)

#FM Regression
fmbobj = FamaMacBeth(temp['Y'],sm.add_constant(temp[['X1','X2','X3','X4','X5','X6']]))
FMBres = fmbobj.fit(cov_type='kernel', kernel='parzen')

print(FMBres)
```

**Comment by bashtage** [comment]
Thanks - I found the issue, a bug (wrong place for parentheses)

**Comment by matbuechner** [comment]
Fabulous! Many thanks
