### ISSUE TITLE
Clustered variance on time ... something is not working right ...

### ISSUE THREAD

**Issue by terminsen** [bashtage/linearmodels#175]
Hi - 

I was trying to replicate some control results regarding the calculation of clustered standard errors in the PanelOls function in the Linearmodels library. Specifically, I was replicating the control results created by Mitchell A. Petersen, made public here: 

https://www.kellogg.northwestern.edu/faculty/petersen/htm/papers/se/test_data.htm

Everything looks fine, but the results from the regression using standard errors clustered by time is a bit off, compared to the other results which are fine. 

Can you please double check if you have the right calculations for standard errors clustering on time, please.   

I assume that I am doing the right things as I was able to replicate all other regression results. 

Running Python 3 and just downloaded LinearModels 4.10 on my Windows computer.

Thank you in advance. 

Kind regards, Jesper.

**Comment by bashtage** [comment]
Can you provide a minimal code example that will generate the discrepancy?

**Comment by terminsen** [comment]
Hi - yes, let me put in the bit about time clustering ... 

    # Fourth: OLS Coefficients and Standard Errors Clustered by Year
    mod = PanelOLS(explained_vars, exog)
    cltime = mod.fit(cov_type='clustered',  cluster_time=True)
    print(cltime)

I have downloaded the dataset from the homepage. 

Best, Jesper.

**Comment by bashtage** [comment]
Could you provide a link to the dataset?

**Comment by terminsen** [comment]
... pushing the dataset link will automatically download the dataset ... I do the following with the data: 

    import pandas as pd
    from linearmodels.panel import PooledOLS
    from linearmodels import FamaMacBeth
    from linearmodels.panel import PanelOLS

    data = pd.read_stata('test_data.dta')
    data = data.set_index(['firmid', 'year'])

    exog_vars = ['x']
    exog = sm.add_constant(data[exog_vars])
    explained_vars = data['y']

I wanted to show the results from all regressions, but when pasting it into this editor it does not look great. All regressions are fine and very much the same as Mitchell A. Petersen´s. But there is a slight difference with the time clustered results. It is close to Petersens result, but compared to the other results it is a bit odd.

**Comment by bashtage** [comment]
The difference is a factor if `sqrt(10)` or if you try  .0317**2/0.0334**2 you get 0.9.  This will be due to dividing somewhere by g or g-1 where g is the number of groups.

**Comment by terminsen** [comment]
I see. Interesting. 
Do you agree on the commands above to reproduce Petersen´s results on the Standard Errors Clustered by Year ? Or, should I do something different to account for the division you found ?

**Comment by bashtage** [comment]
I'll have to look into why this is the case.  It may be intentional (e.g. to match Stata) since I'm surprised that it behaves differently from other clustering.

**Comment by terminsen** [comment]
OK - Thank you for your prompt answers. I appreciate it. 
Best, Jesper Termansen

**Comment by bashtage** [comment]
Good news, no bug.  You need to use `group_debias=True` to divide by `g-1` instead of `g`.  This doesn't appear when clustering by firm since g=5000 and so you can't see the effect in the number of digits reported on the website or when printing.

The results from Petersen can be replicated using 

```
cltime = mod.fit(cov_type='clustered',  cluster_time=True, group_debias=True)
print(cltime)
```

**Comment by terminsen** [comment]
Thank you !!
