### ISSUE TITLE
BUG: Invalid Estimations in Fama Macbeth Regressions

### ISSUE THREAD

**Issue by whoopnip** [bashtage/linearmodels#176]
I have noticed that I am able to get coefficient estimates for variables which vary by time but not by entity, while including a constant. As the first stage regressions are partitioned by time, the variable is a constant, and yet I get a parameter estimate.

It looks like this is happening because `numpy.linalg.lstsq` does not require full column rank for the exogenous matrix. I notice that `FamaMacbeth` inherits from `PooledOLS` which has a `_validate_data` method which checks that the exogenous variables have full column rank. However this check is only completed for the input data, which is not partitioned by time. 

Each time group is passed to `FamaMacbeth.fit.single` to run the first stage regression. Within `single`, there is a check to see whether there is enough observations to run the regression `if exog.shape[0] < exog.shape[1]`. I believe a check to see whether the selected time exogenous matrix has full rank should be added here: `if (exog.shape[0] < exog.shape[1]) or (matrix_rank(exog) < exog.shape[1]):`. In my testing, this fixes the issue.

I'm not sure what your process is. I'm happy to create a PR or add an example if necessary.

**Comment by bashtage** [comment]
A minimal runnable example would be helpful.

**Comment by whoopnip** [comment]
No problem.

```
from linearmodels import FamaMacBeth
import pandas as pd

# Create testing df
df = pd.DataFrame(
    data=[
        ('a', '1/1/2000', 5, 1, 3),
        ('a', '1/2/2000', 6, 3, 21),
        ('b', '1/1/2000', 7, 1, 4),
        ('b', '1/2/2000', 8, 3, 52),
        ('c', '1/1/2000', 9, 1, 2),
        ('c', '1/2/2000', 10, 3, 7),
        ('d', '1/1/2000', 11, 1, 90),
        ('d', '1/2/2000', 12, 3, 10),
    ],
    columns=['Firm', 'Date', 'y', 'x1', 'x2']
)
df['Date'] = pd.to_datetime(df['Date'])
df['cons'] = 1
df.set_index(['Firm', 'Date'], inplace=True)

# Run Fama-Macbeth regression
model = FamaMacBeth(df['y'], df[['cons', 'x1', 'x2']])
model.fit()
```

The above code produces parameter estimates for all parameters. Here `x1` does not vary by firm, only by time. Therefore in the first stage regression for 1/1/2000, it is always 1, and for the first stage regression for 1/2/2000, it is always 3, so it should be impossible to estimate both `x1` and `cons`.

**Comment by bashtage** [comment]
Candidate for a fix in #177.  It will now error if all blocks are not valid (like in your example).

**Comment by whoopnip** [comment]
Looks great to me! Thanks for the quick fix.

**Comment by bashtage** [comment]
Now released.

**Comment by harocksan** [comment]
Hi there, the problem still occurs with the linearmodels 4.19 version. Does anyone experience the same error again?

**Comment by bashtage** [comment]
Can you show example code?

**Comment by harocksan** [comment]
I get the error when I use the example of nickderobertis above and also with my a bit more complicated dataset.

my dataset looks like that:
![image](https://user-images.githubusercontent.com/78083431/105989412-61199600-60a1-11eb-8e84-0b71f17b18bc.png)

I then use the following codes:

```
data = data.set_index(["fundno","date"])

result = FamaMacBeth(data["y"], sm.add_constant(data[["t_dummy", "total_net_assets", "age", "exp_days","size"]])).fit()

```

It works fine with linearmodels PanelOLS though.

**Comment by bashtage** [comment]
What do you get for output?  NaN or error?

**Comment by harocksan** [comment]
I get the error "Model cannot be estimated. All blocks of time-series observations are rank
deficient, and so it is not possible to estimate any cross-sectional regressions."

**Comment by bashtage** [comment]
It is your dummy variable. You can't estimate a time invariante dummy with FMB. Drop this and try again.

**Comment by harocksan** [comment]
you were right, it works without the dummy! Is there no way that dummy variables work with FMB? If so, what other approach is comparable? 

Many thanks!

**Comment by bashtage** [comment]
FMB doesn't work with regressors that do not vary in the cross-section for a fixed time period since it includes time effects.

**Comment by bashtage** [comment]
Put another way, FMB already includes time dummies for all periods do you don't need to include your own.

**Comment by harocksan** [comment]
thank you for your answers! I need to add dummies for some hypotheses like if the fund is team-managed or not (which can vary over time).

**Comment by bashtage** [comment]
You can include dummies but you need cross-sectional variation in the dummies in each time period.  In other word, you need some funds that are team managed and some individually each period.  If you only have team or individual than you cannot estimate that model FMB.

**Comment by harocksan** [comment]
Yes, that is the case for my dummies. Each period, I have a varation of funds having either the dummy 1 or 0. 

The same error occurs when I try FMB in linearmodels excluding dummy variables but including an interaction term of a dummy and a numeric variable (e.g., multiplying variable "size" with a financial crisis dummy where the interaction term equals 0 before and after the financial crisis). Does the error of rank deficiency makes sense to you in this case?

**Comment by huangjiashengg** [comment]
This is my four independent variables, which are used for panel regression. The VIF test results are as follows. I don't understand why these VIF values are still causing errors.
       Variable       VIF
0  SMB_21d_mean  1.357776
1  HML_21d_mean  1.694254
2  MKT_21d_mean  1.111752
3  VMG_21d_mean  1.284629

**Comment by huangjiashengg** [comment]
> No problem.
> 
> ```
> from linearmodels import FamaMacBeth
> import pandas as pd
> 
> # Create testing df
> df = pd.DataFrame(
>     data=[
>         ('a', '1/1/2000', 5, 1, 3),
>         ('a', '1/2/2000', 6, 3, 21),
>         ('b', '1/1/2000', 7, 1, 4),
>         ('b', '1/2/2000', 8, 3, 52),
>         ('c', '1/1/2000', 9, 1, 2),
>         ('c', '1/2/2000', 10, 3, 7),
>         ('d', '1/1/2000', 11, 1, 90),
>         ('d', '1/2/2000', 12, 3, 10),
>     ],
>     columns=['Firm', 'Date', 'y', 'x1', 'x2']
> )
> df['Date'] = pd.to_datetime(df['Date'])
> df['cons'] = 1
> df.set_index(['Firm', 'Date'], inplace=True)
> 
> # Run Fama-Macbeth regression
> model = FamaMacBeth(df['y'], df[['cons', 'x1', 'x2']])
> model.fit()
> ```
> 
> The above code produces parameter estimates for all parameters. Here `x1` does not vary by firm, only by time. Therefore in the first stage regression for 1/1/2000, it is always 1, and for the first stage regression for 1/2/2000, it is always 3, so it should be impossible to estimate both `x1` and `cons`.

Even without an intercept term 'cons', this situation is not allowed. The independent variables need to exhibit clear variation across individuals and are not suitable for variables that only vary over time.
