### ISSUE TITLE
Covariance Estimates FamaMacBeth vs LinearFactorModel

### ISSUE THREAD

**Issue by matbuechner** [bashtage/linearmodels#181]
Hi,

when running FamaMacBeth with inputs from a set of time series regressions analogous to the first step in the LinearFactorModel, there appears to be an issue with the covariance estimate for the second stage parameters. Comparing the two approaches I can obtain identical parameter  estimates (risk premia) but there is a discrepancy in the standard errors (obviously, assuming the same cov_type/ kernel parameter is used). 

For example please see below the output from first running a time series regression and then feeding the betas to the FamaMacBeth function

factor                   |parameter | std_error  |   tstat   |     pvalue
------------ | -------------| -------------| -------------| -------------
X_1      |  0.425711  | 0.340993  |1.248444 | 2.119266e-01
X_2      |   -0.645416|   0.294828| -2.189129 | 2.863339e-02
X_3      |    0.519397 |  0.412518| 1.259088  |2.080571e-01
X_4     |     0.476740 |  0.716597 | 0.665284  |5.058993e-01
X_5       |    5.427486  | 0.821842 | 6.604049 | 4.414846e-11
X_6 | -1.205829  | 0.346899 | -3.476028 | 5.132095e-04

And now below the output from LinearFactorModel using the same inputs 

factor                   |parameter | std_error  |   tstat   |     pvalue
------------ | -------------| -------------| -------------| -------------
X_1      |   0.425711  | 0.402419  | 1.057881  | 0.290161
X_2        |   -0.645416  |  0.451214  |-1.430398  | 0.152665
X_3      |      0.519397   | 1.492575  | 0.347987  | 0.727865
X_4      |      0.476740   | 2.892115 |  0.164841  | 0.869075
X_5      |      5.427486  |  3.202529   |1.694750  | 0.090185
X_6  | -1.205829   |0.665081  |-1.813055  | 0.069883

In both cases I use cov_type='kernel' and kernel='bartlett'. As can be seen the parameter estimates agree, the errors do not. I have encountered this problem for a wide range of factors / test assets.

Any help would be much appreciated.

**Comment by bashtage** [comment]
Can you post code to replicate? If you don't use a kernel do you get the
same results? Are the kernel bandwidths the same?

**Comment by bashtage** [comment]
I'm not convinced that the estimated standard errors have to be the same from these two methods even if the point estimates are the same.  The point estimates do not depend on the estimator, and so it is plausible that the two covariance estimates are both consistent even if they differ in finite samples.

**Comment by bashtage** [comment]
LFM estimates nportfolio regressions and then estimates 1 additional to get the RP.  The standard errors account for the dependence between the estimated betas in the 1st stage and the estimation errors in the 2nd stage using a GMM-based approach (see Cochrane).

**Comment by bashtage** [comment]
Details [here](https://bashtage.github.io/linearmodels/asset-pricing/mathematical-formula.html#linear-factor-model-for-non-traded-factors)

**Comment by matbuechner** [comment]
Thanks! Very welcome :)

Matthias Büchner
_________________________________

Mail: mat.buechner@gmail.com
Mobile: +44 7856 737053
Web: linkedin.com/in/matthiasbuechner

**Comment by bashtage** [comment]
Going to close since no action.
