### ISSUE TITLE
PanelOLS with two-way fixed effects / double clustered std. errors for a panel of millions of observations

### ISSUE THREAD

**Issue by matbuechner** [bashtage/linearmodels#182]
Hi, I have come across a performance issue in regards to two-way fixed effects and double clustered standard errors. So essentially I would like to use both entity and time effects as well as double clustered errors in PanelOLS. My panel is unbalanced with about 10 million observations in total, ~5000 entities, ~2000 time steps and say about half a dozen independent variables. 

When running this setup in PanelOLS I keep having trouble with the Python process memory blowing up, ultimately resulting in the Python process being killed by my machine. I suppose this should be replicable using other data sets. For now, please see below a minimal example with a generic set of data available here (sorry for the large file, but this appears to be a large data issue):
[https://www.dropbox.com/s/u9mzwdlyqp1ylu3/LargePanel.csv?dl=0](https://www.dropbox.com/s/u9mzwdlyqp1ylu3/LargePanel.csv?dl=0)

```python
import pandas as pd

from linearmodels import PanelOLS

data = pd.read_csv('LargePanel.csv')
data['Time'] = pd.to_datetime(data['Time'])
data.set_index(['EntityNo', 'Time'], inplace=True)


mod = PanelOLS(data['Y1'], data[['X1', 'X2', 'X3', 'X4']],
               entity_effects=True, time_effects=True)
res1 = mod.fit(cov_type='clustered', cluster_entity=True, cluster_time=True)
```

I would be interested to learn whether there is a way to make the procedure more memory / computationally efficient.

**Comment by bashtage** [comment]
Short term solution is to use one of entity_effects=True and pass the time effect as an `other_effects` value.  This triggers a somewhat slower approach that never builds dummy variable matrices. But it also avoids lots of memory allocation. 

Longer term solution is to automatically switch to the slow method when the dimensions of the effects is large, and to expose a user option to override the automatic choice.

**Comment by matbuechner** [comment]
Thanks!

**Comment by bashtage** [comment]
This fixed in master now.  Can use `low_memory=True` in `fit` or it will automatically use low memory if the dummy variable matrix is > 1GiB (which yours easily is ~10M by 4000 = 320GiB)
