### ISSUE TITLE
How to perform wald test for selected joint coefficients?

### ISSUE THREAD

**Issue by smn-snkl** [bashtage/linearmodels#184]
Is there an easy way to calculate not the F-test, but instead just the hypothesis that a few coefficients jointly equal 0?

**Comment by bashtage** [comment]
There isn't a method to do this -- so would need to use a manual walk of the form (RB)'(R V R)^(-1)(RB). Alternatively would estimate the null and alternative models and use the usual F-stat.

**Comment by smn-snkl** [comment]
Thanks @bashtage! If I remember correctly the usual F-stat wouldn't work with clustered variances though, right?

**Comment by bashtage** [comment]
Yes.  In this case you need the quadratic form directly . I'll leave this
open since a helper function should be pretty easy and useful.

**Comment by bashtage** [comment]
This has been fixed in master -- `wald_test` can be used for IV and panel models.
