### ISSUE TITLE
Title of summary table for `IV-2SLS` and the Name of `Estimator` inside the output table

### ISSUE THREAD

**Issue by spring-haru** [bashtage/linearmodels#185]
In the [manual](https://bashtage.github.io/linearmodels/doc/iv/examples/basic-examples.html) `Basic Examples` of `Instrumental Variable Estimation`, the following code

```
res_ols = IV2SLS(np.log(data.wage), data[['const','educ']], None, None).fit(cov_type='unadjusted')
print(res_ols)
```
gives the output with the titile `OLS Estimation Summary` and `Estimator: OLS` inside the table. This is a great feature.

However, If I run the following with a formula

```
formula = 'np.log(data.wage) ~ 1 + educ'
res_formula = IV2SLS.from_formula(formula, data).fit(cov_type='unadjusted')
print(res_formula)
```

the result has the title `IV-2SLS Estimation Summary` and `Estimator: IV-2SLS`. (Obviously, both codes give exactly the same result.) I wonder if there is a way to change the title to `OLS Estimation Summary` and the `Estimator` part inside the table to `Estimator: OLS`.

**Comment by bashtage** [comment]
Thanks.  #186  will fix this in master.
