### ISSUE TITLE
Singleton Observations in Fixed Effect Models

### ISSUE THREAD

**Issue by justan0theruser** [bashtage/linearmodels#191]
Does **linearmodels** account for singleton observations in fixed effect models?

I am familiar with the **reghdfe** [Stata command](https://github.com/sergiocorreia/reghdfe), but I'm trying to make the full switch to Python. The author of that package also has a [brief paper](http://scorreia.com/research/singletons.pdf) discussing the issue.

As I compare the results of the two implementations, they start off identical and gradually diverge with more complicated models. I'm not entirely sure singleton observations are to blame for the differences, but it seems plausible.

**Comment by bashtage** [comment]
Are you comparing the results against reghdfe or xtreg?

**Comment by bashtage** [comment]
There is an option that can be set to `singletons=False` that will remove singleton observations.

**Comment by bashtage** [comment]
@justan0theruser This has been added for PanelOLS. It is a bit experimental, so if you use it, please let me know how it works for you (esp speed).
