### ISSUE TITLE
`.wu_hausman` in `IV2SLS` gives a wrong output

### ISSUE THREAD

**Issue by spring-haru** [bashtage/linearmodels#192]
`.wu_hausman` in `IV2SLS` generates a table of `IV2SLS` results rather than test statistics, p-value, etc of the test. Can you have a look into this?

**Comment by bashtage** [comment]
Are you calling wu_hausman()? If not you get the model repr which is a
summary.

**Comment by spring-haru** [comment]
Thanks.
I assumed that `.wu_hausman` behaved just like `.sargan`, `.wooldridge_regression` and others.

**Comment by bashtage** [comment]
Tests that have inputs, even if optional, are functions, while statistics that cannot vary are properties (e.g, parameters, tstats, and sargan).
