### ISSUE TITLE
Poolability test in PoolOLS

### ISSUE THREAD

**Issue by avneeshs1** [bashtage/linearmodels#202]
Kevin, I was wondering if linearmodels (or really anything else) implements the standard Chow test for poolability as in http://support.sas.com/documentation/cdl/en/etsug/66840/HTML/default/viewer.htm#etsug_panel_details41.htm.

I see that FixedEffects model has an F-test for effects but was looking for testing whether pooled ols is appropriate or not. 

Thanks for writing this wonderful package. It plugs a big hole in statsmodel currently!

**Comment by bashtage** [comment]
The F-test for poolability is a standard output of `PanelOLS`. If the effects pool -- and so the null isn't rejected -- then a PooledOLS is appropriate.

**Comment by bashtage** [comment]
If you are looking for a test whether a model with 2 effects can be pooled to a model with 1, then you will need to directly implement this using teh sum of squared residuals.

**Comment by avneeshs1** [comment]
With no effects turned on, I don't see the pooled Ftest. See below: 

![image](https://user-images.githubusercontent.com/13733034/55164715-8904df00-5142-11e9-8800-4eb0f8af9b65.png)

Whereas if I turn on entity effects, I see the F-test.
![image](https://user-images.githubusercontent.com/13733034/55164856-cbc6b700-5142-11e9-911d-e421b1ee1c6f.png)

I was thinking of a simple pooled test for when all effects are turned off. For now, I will implement the test directly.

**Comment by bashtage** [comment]
The test is effect specific, so I cannot be implemented without known the effects you want to test, e.g. entity effects, or possibly some other effect.  For this reason, it is only available after running PanelOLS with 1 or more effects.

**Comment by avneeshs1** [comment]
Sorry. I realize that I am not being clear. Assume the pooled regression model is (without any fixed effects):

y_it = a + b x_it + u_it. i is the entity and t is the time

This can be compared to the unrestricted model where say regression coefficients are split up by entities:

y_it = a_i + b_i x_it + u_it. 

Then, we can run the standard Chow test to see if the pooled regression is appropriate or not. 

This is what I was hoping to see out-of-the-box. Currently, the implemented f-tests only test for different intercepts not different coefficients...

**Comment by bashtage** [comment]
That is clearer.  What you are describing a a *fixed slope*, not a fixed effect.  I don't have any plans for fixed slopes.

**Comment by avneeshs1** [comment]
Ok. Thanks for clarifying. I will close the ticket.
