### ISSUE TITLE
scipy's factorial function no longer in misc

### ISSUE THREAD

**Issue by toddrme2178** [bashtage/linearmodels#209]
The `factorial` function is no longer in `scipy.misc.` [as of scipy 1.3.0](https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html#scipy-interpolate-changes).  It has lived in [`scipy.special`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.factorial.html) since scipy 1.0.0, but the alias in `scipy.misc` was removed in 1.3.0.  This causes the tests to fail.

**Comment by bashtage** [comment]
What version are you using. This is fixed in master and in the latest release.

**Comment by bashtage** [comment]
I don't use factorial. Is this a statsmodels bug?

**Comment by toddrme2178** [comment]
Yes it is, sorry about the noise.

**Comment by bashtage** [comment]
Also fixed in statsmodels but only in 0.10.
