### ISSUE TITLE
biprobit or similar for binary endogenous explanatory variable

### ISSUE THREAD

**Issue by lepmik** [bashtage/linearmodels#212]
Hi,

I've asked the same question on pystatsmodels [forum](https://groups.google.com/forum/#!topic/pystatsmodels/-wGCNWu7wiY), sorry if it is inconvenient to use the issue tracker here for the purpose of this question.

I have a model similar to what is described in Wooldridge (econometric analysis of cross section and panel data 2nd ed.) 15.7.3 (eqs. 15.51 and 15.52). There it is said that a bivariate probit model can be used to estimate parameters. Is this or something similar implemented in linearmodels, or are you planning to implement it? e.g. systems probit/logit

Best

**Comment by bashtage** [comment]
No plans to add non-linear models.
