### ISSUE TITLE
Adding the name of the dependent variable to 'fit' output

### ISSUE THREAD

**Issue by blucap** [bashtage/linearmodels#251]
Just a simple request: would it be possible to include the name of the dependent variable in the list of items that `fit` holds? 

See this list [here](https://bashtage.github.io/linearmodels/doc/iv/results.html?highlight=tstats#linearmodels.iv.results.OLSResults). It contains many itmes, such as params, nobs, etc ... , except for the dependent variable ... .

I now rely on `[formula[:formula.find('~')].strip()]` but that is kind of ugly.

**Comment by bashtage** [comment]
`formula.split('~')[0].strip()` is smaller.

**Comment by bashtage** [comment]
Can directly access it in a results instance using

`res.model.dependent.vars[0]`

or from a model as 

`mod.dependent.vars[0]`
