### ISSUE TITLE
ENH: Add support for 2-way Random Effects model

### ISSUE THREAD

**Issue by karasjoh000** [bashtage/linearmodels#252]
Hi, 

I am working with random and fixed effects. Is there a way to control for entity effects and time effects in the random effect model? The fixed effects have it but random doesn't. How should I approach this problem? 

I am trying to compare the fixed effects and random effects with entity effects only, time effects only, and then both time and entity effects.

**Comment by karasikHacker** [comment]
looking at the code it seems like there should be a way from using the `from_formula` method. It passes it into a parser that then decides what effects to set on it. 

```python
    def _parse(self) -> None:
        parts = self._formula.split("~")
        parts[1] = " 0 + " + parts[1]
        cln_formula = "~".join(parts)

        mod_descr = ModelDesc.from_formula(cln_formula)
        rm_list = []
        effects = {"EntityEffects": False, "FixedEffects": False, "TimeEffects": False}
        for term in mod_descr.rhs_termlist:
            if term.name() in effects:
                effects[term.name()] = True
                rm_list.append(term)
        for term in rm_list:
            mod_descr.rhs_termlist.remove(term)
```

**Comment by karasikHacker** [comment]
I basically want to first do "EntityEffects" only using `RandomEffects` model, then only "TimeEffects", and lastly use both "EntityEffects" and "TimeEffects" with `RandomEffects`

**Comment by bashtage** [comment]
I only have 1-way RE models. For 2-way models only FE are available. The formula parse can't change the internals of `RandomEffects()`

**Comment by bashtage** [comment]
You probably can model it using statsmodels:

https://www.statsmodels.org/stable/mixed_linear.html

**Comment by bashtage** [comment]
I don't think 2-way RE are a goal of this project.  Mixed Linear models are available in statsmodels.
