### ISSUE TITLE
Pandas 1.0, 1.0.1 MultiIndex setting

### ISSUE THREAD

**Issue by cconw** [bashtage/linearmodels#253]
There appears to be some deprecated multiindex functionality in pandas (1.0, 1.0.1) which conflicts with the linearmodels package.  Reverting back to pandas version 0.25 restores the functionality of the package.  To recreate:

import numpy as np
import pandas as pd
from linearmodels import PanelOLS
data = {'y':[1,2,3,1,0,3],
        'x1': [0,1,2,3,0,2],
        'x2':[1,1,3,2,1,0],
        't': pd.to_datetime(['2020-02-18', '2020-02-18', '2020-02-17', '2020-02-18', '2020-02-18', '2020-02-17']),
        'province': ['A', 'A','A','B','B','B'],
        'city': ['a','b','a','a','c','a']}
dataframe = pd.DataFrame (data, columns = ['y','x1', 'x2', 't', 'province', 'city'])
dataframe["city-provence"] = [(c,p) for c,p in zip(dataframe.city, dataframe.province)]
dataframe = dataframe.set_index(['city', "t"])
dataframe
exog_vars = ['x1','x2']
exog = dataframe[exog_vars]
mod = PanelOLS(dataframe.y, dataframe[['x1','x2']], entity_effects = True)
mod_res = mod.fit()
print(mod_res)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-60920f7211b8> in <module>
      1 exog_vars = ['x1','x2']
      2 exog = dataframe[exog_vars]
----> 3 mod = PanelOLS(dataframe.y, dataframe[['x1','x2']], entity_effects = True)
      4 mod_res = mod.fit()
      5 print(mod_res)

~\Anaconda3\lib\site-packages\linearmodels\panel\model.py in __init__(self, dependent, exog, weights, entity_effects, time_effects, other_effects, singletons, drop_absorbed)
    760     def __init__(self, dependent, exog, *, weights=None, entity_effects=False, time_effects=False,
    761                  other_effects=None, singletons=True, drop_absorbed=False):
--> 762         super(PanelOLS, self).__init__(dependent, exog, weights=weights)
    763 
    764         self._entity_effects = entity_effects

~\Anaconda3\lib\site-packages\linearmodels\panel\model.py in __init__(self, dependent, exog, weights)
    170 
    171     def __init__(self, dependent, exog, *, weights=None):
--> 172         self.dependent = PanelData(dependent, 'Dep')
    173         self.exog = PanelData(exog, 'Exog')
    174         self._original_shape = self.dependent.shape

~\Anaconda3\lib\site-packages\linearmodels\panel\data.py in __init__(self, x, var_name, convert_dummies, drop_first, copy)
    223         levels = self._frame.index.levels
    224         for i in range(2):
--> 225             levels[i].name = index_names[i]
    226 
    227     @property

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in name(self, value)
   1189             # Used in MultiIndex.levels to avoid silently ignoring name updates.
   1190             raise RuntimeError(
-> 1191                 "Cannot set name on a level of a MultiIndex. Use "
   1192                 "'MultiIndex.set_names' instead."
   1193             )

RuntimeError: Cannot set name on a level of a MultiIndex. Use 'MultiIndex.set_names' instead.

**Comment by bashtage** [comment]
Which version of linearmodels are you using?  It is definitely fixed in master, and I think in 4.17 as well.

**Comment by bashtage** [comment]
Works in the latest release and pandas 1.0.1.

**Comment by bashtage** [comment]
Fixed in 2626748

https://github.com/bashtage/linearmodels/commit/26267483e34c9f44037bb8cee2d01ff170d81acb#diff-74a46690e88d8947d7d5e532b291b9f4R223

**Comment by cconw** [comment]
> Which version of linearmodels are you using? It is definitely fixed in master, and I think in 4.17 as well.

You are correct.  Sorry.  I thought I updated it and it was a 4.14 issue.  For some reason when I removed and reinstalled the package (trying to capture and recreate this issue), it didn't pull the latest version.  Not sure why.  Thanks for your quick response.
