### ISSUE TITLE
Question: one sided t-statistic on Random effects coefficient. 

### ISSUE THREAD

**Issue by karasjoh000** [bashtage/linearmodels#256]
Question: When testing whether a coefficient is larger than a particular value we run a one-tailed t-test (based on wald statistic) to see whether we can reject the null. How can this test be preformed given the random effects results object (returned from fit method of RandomEffects)?

**Comment by karasjoh000** [comment]
The model also can have autocorrelation and heteroskadicity so we will need to newey HAC estimate of cov for the t-statistic.

**Comment by bashtage** [comment]
Please start with the docs:

https://bashtage.github.io/linearmodels/panel/panel/linearmodels.panel.results.RandomEffectsResults.html#linearmodels.panel.results.RandomEffectsResults

You will see one of the outputs in tvales. You can implement a 1-sided test as wither stats.norm.cdf(tvalue) (lower) or 1 - stats.norm.cdf(tvalue) (upper).

The Driscoll-Kraay estimator is a HAC.
