### ISSUE TITLE
RuntimeError: Cannot set name on a level of a MultiIndex. Use 'MultiIndex.set_names' instead.

### ISSUE THREAD

**Issue by skantbksc** [bashtage/linearmodels#261]
I am getting the following error when I try to run a panel regression:
RuntimeError: Cannot set name on a level of a MultiIndex. Use 'MultiIndex.set_names' instead.
How can this be fixed?

**Comment by bashtage** [comment]
Use an older pandas or upgrade to linearmodels master.

**Comment by skantbksc** [comment]
Thanks. But how can I upgrade to linearmodels master.

**Comment by bashtage** [comment]
`pip install git+git://github.com/bashtage/linearmodels.git --upgrade`
