### ISSUE TITLE
ValueError: Series can only be used with a 2-level MultiIndex

### ISSUE THREAD

**Issue by CodeKaushik** [bashtage/linearmodels#265]
#for fixed pooled regression
from linearmodels import PanelOLS
mod = PanelOLS(df["ROA"], x) entity_effects=True)
res = mod.fit(cov_type='clustered', cluster_entity=True)

I trying my hands on Pooled Data analysis for the first time and I'm not able to work around this MULTI-INDEX ERROR

x here is the set of independent variabel (A DATAFRAME)
and my dependent variable here is df[ROA]
![independent set](https://user-images.githubusercontent.com/65309471/81855941-ab8fcc80-957d-11ea-9acd-fdadd6119a0e.jpg)

![dataset](https://user-images.githubusercontent.com/65309471/81856074-e1cd4c00-957d-11ea-933d-831f1bb93268.jpg)

**Comment by bashtage** [comment]
Please see the examples in the documentation that explains the requirements for the index in panel models.

 https://bashtage.github.io/linearmodels/panel/examples/data-formats.html
