### ISSUE TITLE
AttributeError: 'PanelEffects Results' object has no attribute 'deferred_cov'

### ISSUE THREAD

**Issue by CaoGaoxu** [bashtage/linearmodels#266]
Description:
I am creating a panel regression with fix effects and would like to see the results details like model fitted values.  The model is built by using PanelOLS and I can see the PanelOLS Estimation Summary without any problems. However, when I try to use the PanenlEffectsResults to get the fitted values. I am getting an _AttributeError:'PanelEffects Results' object has no attribute 'deferred_cov'. 

Source Code:
```python
from linearmodels.panel import RandomEffects
from linearmodels.panel.results import (
    FamaMacBethResults,
    PanelEffectsResults,
    PanelResults,
    RandomEffectsResults,
)

mod = PanelOLS(dependent, exog, entity_effects =True)
res = mod.fit(cov_type='unadjusted')
panel_res = PanelEffectsResults(res)
panel_res.fitted_values
```
AttributeError: 'PanelEffectsResults' object has no attribute 'deferred_cov'

Thank you for your help!

**Comment by bashtage** [comment]
res is already a PenelEffectsResults.  There is no need to directly use these classes.

**Comment by CaoGaoxu** [comment]
I see. Thanks a lot!
