### ISSUE TITLE
USE of GENERALISED METHOD OF MOMENT for estiamtion for Panel Data

### ISSUE THREAD

**Issue by CodeKaushik** [bashtage/linearmodels#267]
I'm have been asked to use GMM (GENERALISED METHOD OF MOMENT) for parameter estimation for a panel data to compare the results with the model from ,FIXED PANEL REGRESSION and Pooled Panel Regression.
I have been able to perform the above two but can't seem to get it done via.

I have attached the images of dataset, independent set of vairables , and the way want my results.

is there a way(code) to get these via GMM?

![independent set](https://user-images.githubusercontent.com/65309471/81971325-8747f480-963e-11ea-96cd-5440012719eb.jpg)
![Result](https://user-images.githubusercontent.com/65309471/81971335-89aa4e80-963e-11ea-968b-16abe067b7ea.jpg)
![dataset](https://user-images.githubusercontent.com/65309471/81971336-8a42e500-963e-11ea-87fd-5cd4775776f9.jpg)

**Comment by bashtage** [comment]
No.  This is a dynamic panel model and there is no support for these in this package.

**Comment by CodeKaushik** [comment]
I'm new  to github , can you help me where i'm supposed to post this issue?

**Comment by bashtage** [comment]
You can estimate the model you want in R.  Just look for dynamic panel.
