### ISSUE TITLE
changing the level of clustering in PanelOLS

### ISSUE THREAD

**Issue by madinajapakhova** [bashtage/linearmodels#272]
Is there a way/syntax to change the cluster variable for clustered standard errors? 
```
df= df.set_index(['branchid', 'villageid'], drop = False) 
reg = PanelOLS(df.outcome, df.treatment, entity_effects = True) 
res = reg.fit(cov_type = 'clustered',cluster_entity = True) 
print(res)
``` 
As a result the standard errors are clustered at the branchid level, which is fine, but ideally I'd like to have them clustered at the villageid level. Is there a way to pass "villageid" as a cluster? I looked up here: https://bashtage.github.io/linearmodels/doc/panel/models.html#linearmodels.panel.model.PanelOLS  , where it mentions that _covariance estimator "clustered"_ has a configuration option _clusters_ . However, I didnot find its syntax. Thanks!

**Comment by bashtage** [comment]
You can cluster on any variable. There is an example here:

https://bashtage.github.io/linearmodels/panel/examples/examples.html#Other-clusters

**Comment by bashtage** [comment]
Closing as answered.
