### ISSUE TITLE
"drop_absorbed" flag for AbsorbingLS

### ISSUE THREAD

**Issue by codyfcook** [bashtage/linearmodels#276]
Fully absorbed variables in AbsorbingLS raises an 'AbsorbingEffectError' error, which includes the recommendation to set drop_absorbed=True. This is not currently an option for AbsorbingLS. 

I believe the logic from PanelOLS could be ported over ([relevant code](https://github.com/bashtage/linearmodels/blob/7705cacb4a7a4aafafbf8b9a1c5d7a5d080f3e95/linearmodels/panel/model.py#L1694))

**Comment by bashtage** [comment]
Can you provide some example code?
