### ISSUE TITLE
Panel regression results

### ISSUE THREAD

**Issue by aminnejat** [bashtage/linearmodels#281]
Hello,

First of all, thanks for the very helpful package. 

I am using PanelOLS class to run a panel regression, under fixed effect circumstances. I got the beta in the results summary, but I could not fin alpha(i), so I was wondering how I can access the fixed effect value for each of my data group.

Thanks in advance.

**Comment by bashtage** [comment]
See the [`estimted_effects` property](https://bashtage.github.io/linearmodels/panel/panel/linearmodels.panel.results.PanelResults.estimated_effects.html)
