### ISSUE TITLE
Panel regression results

### ISSUE THREAD

**Issue by aminnejat** [bashtage/linearmodels#282]
Hello again,

Thank you so much for your quick reply. sorry but I still have an issue with PanelOLS results and since the previous one is closed I opened a new one. When I use the Estimated effects property, the result shows estimated effect for each line of my data. But since my data includes only two different data clusters, I expected just two alphas, am I missing a point here? My results look like this.

                                    estimated_effects
Date       Currency                   
1986-11-20 1                  0.719170
1986-12-18 1                  0.722693
1987-01-22 1                  0.733991
1987-02-26 1                  0.749865
1987-03-26 1                  0.764874
...                                ...
1997-06-24 0                  0.721812
1997-07-23 0                  0.726492
1997-08-22 0                  0.719652
1997-09-24 0                  0.722677
1997-10-28 0                  0.711423

**Comment by bashtage** [comment]
Effects are removed and not estimated directly.  This avoids lots of memory allocation in large panels.  If one of your dimensions is small, e.g., small number of time periods and one is big, lots of firms, then you can include regressors for the small dimension and the effects will be the effect.

The reason they are not reported is that they are not consistently estimated, and so they are not model parameters.  The FE estimator is a device to recover other parameters which not modeling the effect.

You could also regress the effects on dummies to recover the individual effects.

**Comment by aminnejat** [comment]
That makes sense. Thank you for the explanation.
