### ISSUE TITLE
Question about Entity and Time Effects

### ISSUE THREAD

**Issue by amichuda** [bashtage/linearmodels#283]
First off, I really like package and it's been great to fixed effects regression natively in Python.

I have a question/suggestion: why do you require the the use of multiindex dataframes for use with fixed effects regression, rather than just supplying a column name for which column to demean over or create dummies for? Based on the `demean` function, you're doing a groupby-transform when you're demeaning which doesn't require indices to be set. 

This isn't meant as a criticism, I really like the package! I just wanted to get your rationale if you have time.

**Comment by bashtage** [comment]
Because allowing columns would require two additional inputs into the
signature, one for the entity column and one for time.  The signature is
already fairly large without these two additional inputs.

**Comment by bashtage** [comment]
The two are also only separated by a single call to `set_index` or `reset_index`.
