### ISSUE TITLE
first_difference() of PanelData object generates an error

### ISSUE THREAD

**Issue by spring-haru** [bashtage/linearmodels#285]
I get an error if `.first_differece()` is used on `PanelData` object.
 Consider the following example:

```
import numpy as np
import pandas as pd
from linearmodels.panel.data import PanelData

n = 4
df = pd.DataFrame({'country':['A']*n+['B']*n+['C']*n,
                   'year':[2000,2001,2002]*n,
                   'v1':np.random.random(3*n),
                   'v2':np.random.random(3*n)*100}).set_index(['country','year'])

dfp = PanelData(df)
dfp.first_difference()
```

This gives
```
ValueError: cannot handle a non-unique multi-index!
```

Other attributes and methods seem to work, as expected.

A bug or am I missing something?

linearmodels: 4.17

**Comment by bashtage** [comment]
Yes. This is expected since you have multiple entity-year entries so it isn't clear what first difference should mean.

**Comment by bashtage** [comment]
Is there a reasonable interpretations in this case?  Perhaps I missed something.

**Comment by spring-haru** [comment]
My code above was wrong. Sorry for bothering you. Thanks anyway.
