### ISSUE TITLE
Fixed effects implementation

### ISSUE THREAD

**Issue by Econ808** [bashtage/linearmodels#290]
Hi,

I have been comparing results of R's `plm` package with `PanelOLS`. Overall the results are similar, however, `PanelOLS` is faster by a factor of approx. 45, which made me wonder how this could be? I tried looking at the source code, but naturally it is a bit convoluted, so I hoped that you might be able to explain why there is such a difference in the speed? To my best knowledge both use the within transformation?

Best regards

**Comment by bashtage** [comment]
I don't know. I've never looked at the plm source code since it isn't compatible with linearmodel's license. I defer the transformation to pandas, so pandas performance in groupby operations will affect the performance of linearmodels. This said, I mostly use LSMR in panel models with 2 effects, which I have found to be faster than grouping.

**Comment by Econ808** [comment]
Hmm, that is interesting. How come the implementation of PanelOLS does not use the LSMR instead - as I assume the result is the same? And do you have an example of LSMR used for fixed effects estimation in python?

**Comment by bashtage** [comment]
I don't understand your comment.  `PanelOLS` _does_ use LSMR.  This is why is it often fast. When I say "I" I mean the code I wrote in linearmodels.

**Comment by Econ808** [comment]
Ah, I see - I guess I was just confused by your previous answer, namely that `pandas.DataFrame.groupby` was used for the within-transformation. Then mentioning that LSMR is faster than grouping, I assumed that you meant `pandas.DataFrame.groupby` and was therefore confused. When you say grouping, do you mean LSDV regression?

**Comment by bashtage** [comment]
In balanced panels or 1-way effects models groupby demean is the same as LSDV.  In unbalanced panels it has to be implemented iteratively to be equivalent to LSDV.  LSMR is a fast way to estimate high-dimensional LSDV models using gradient descent., and so never requires inverting a matrix.
