### ISSUE TITLE
PanelOLS predict

### ISSUE THREAD

**Issue by Econ808** [bashtage/linearmodels#291]
Hi,

I want to simulate a few datapoints, and was hoping to be able to use the `predict` functionality from `PanelOLS`, however, a ValueError is raised when i use predict the way I would in `Statsmodels`. What am I doing wrong?

![image](https://user-images.githubusercontent.com/36441764/99515386-2dc5d700-298d-11eb-88da-55d713a7f1c7.png)

The Error:

![image](https://user-images.githubusercontent.com/36441764/99515159-e4758780-298c-11eb-88bb-1fa19c2907fe.png)

**Comment by Econ808** [comment]
I seem to have successfully calculated the predictions with the dot product:

![image](https://user-images.githubusercontent.com/36441764/99528552-bdc04c80-299e-11eb-88a3-5cf4166332aa.png)

I will leave this open, as I assume that it is either a bug, or that there is a need for the documentation to mention the correct input format to predict.

**Comment by bashtage** [comment]
Can you possible post a copy and paste reproducer?

**Comment by Econ808** [comment]
```
df["id"] = df["cprnr_aar_maaned"].astype("category").cat.codes
df = df.set_index(["id", "Dato"])

dependent = df.Ulovligt_fravaer
exog = sm.add_constant(df[["wind", "Rain", "sun", "temp_max", "temp_max_squared"]])
mod = PanelOLS(dependent, exog, entity_effects=True, drop_absorbed=True)
res_double = mod.fit(cov_type="clustered", cluster_entity=True, cluster_time=True)

median_wind = df.wind.median()
median_rain = df.Rain.median()
median_sun = df.sun.median()
const = res_double.params["const"]
predict_matrix = np.array(
    [
        [const, median_wind, median_rain, median_sun, temp, temp ** 2]
        for temp in range(-6, 34)
    ]
)
# Predict fails
res_double.predict(predict_matrix)
# Predict succeeds
predictions_absence = predict_matrix @ res_double.params.values

```

**Comment by bashtage** [comment]
One last ask - > Can you create a fake DF like the one you are using?  Fine to fill with random values.

**Comment by Econ808** [comment]
Okay 2 sec.

**Comment by Econ808** [comment]
Took me more than a few secs to actually create something fake that actually works:


```
df_rand_absence = pd.concat([pd.DataFrame(
    {
        'Ulovligt_fravaer':(np.random.randint(0,2, 200)).astype(bool),
        'Dato':pd.date_range(start='01-01-2016', periods=200, freq='D'),
        'id':id
    })
    for id in range(1000)
])
df_rand_weather = pd.DataFrame(
    {
        'Dato':pd.date_range(start='01-01-2016', periods=200, freq='D'),
        'wind':np.random.choice(df.wind.values, 200),
        'Rain':np.random.choice(df.Rain.values, 200),
        'sun':np.random.choice(df.sun.values, 200),
        'temp_max':np.random.rand(200)*30
    }
)
df_rand = pd.merge(df_rand_absence, df_rand_weather, how='left', on='Dato')
df_rand['temp_max_squared'] = df_rand['temp_max']**2

df_rand = df_rand.set_index(["id", "Dato"])

dependent = df_rand.Ulovligt_fravaer
exog = sm.add_constant(df_rand[["wind", "Rain", "sun", "temp_max", "temp_max_squared"]])
mod = PanelOLS(dependent, exog, entity_effects=True, drop_absorbed=True)
res_double = mod.fit(cov_type="clustered", cluster_entity=True, cluster_time=True)

median_wind = df_rand.wind.median()
median_rain = df_rand.Rain.median()
median_sun = df_rand.sun.median()
const = res_double.params["const"]
predict_matrix = np.array(
    [
        [const, median_wind, median_rain, median_sun, temp, temp ** 2]
        for temp in range(-6, 34)
    ]
)
# Predict fails
res_double.predict(predict_matrix)
# Predict succeeds
predictions_absence = predict_matrix @ res_double.params.values

```

**Comment by bashtage** [comment]
Thanks.  This is very helpful and it will let me track down the bug quickly.

**Comment by bashtage** [comment]
This issue is that `predict_matrix` must be compatible with a `PanelData` object of the correct size.  It is best to pass in a MultiIndex dataframe here with the right entity and time ids.

This is essentially the same as #292

**Comment by bashtage** [comment]
If you do something like

```
import pandas as pd

mi = pd.MultiIndex.from_tuples([(i,0) for i in range(predict_matrix.shape[0])])
predict_matrix = pd.DataFrame(predict_matrix, index=mi)
```

you should get it to work.  It can be pretty much any 2-level MultiIndex as long as it is compatible with the `PanelData` object.
