### ISSUE TITLE
panelOLS.predict()  Help wanted

### ISSUE THREAD

**Issue by machenyufitz** [bashtage/linearmodels#292]
Hi Kevin, 

As I've built a fixed-effect regression model for panel data, I want to use the panelOLS.predict() method to predict dependent variable values for different dataframes. I tried passing in 5 columns in a list as the input parameters, but it raised a ValueError. 

I have three dataframes with the same column attributes:
df10 represents data of year 2010. 
![2](https://user-images.githubusercontent.com/58746879/101549601-d2bb4a80-3962-11eb-94ce-8b56f2838ddf.PNG)

df16 represents data of year 2016. 
![3](https://user-images.githubusercontent.com/58746879/101549616-d9e25880-3962-11eb-8af8-6bd4ce68e899.PNG)

df is a multi-level index dataframe contains both year 2010 and 2016 data. This df is used to build the fixed_effect model. 
![4](https://user-images.githubusercontent.com/58746879/101549628-de0e7600-3962-11eb-89b3-aa87c5a42703.PNG)

### Codes:

Creating multi-level index to define the entities and the time periods
```
df10['YEAR'] = df10['YEAR'].astype(int)
df16['YEAR'] = df16['YEAR'].astype(int)
df = df10.append(df16, ignore_index=True)
df = df.set_index(['ID', 'YEAR'])
df = df.sort_index()
```

 Building the fixed-effect model.
 Both dependent and independent variables are dataframe columns.
```
mod_entity= "PanelOLS.from_formula("INRIX_VOL \
                       ~ CHAMP_VOL \
                       + TNC_VOL\
                       + AVG_DUR_MAJOR_ARTERIALS \
                       + AVG_DUR_MINOR_ARTERIALS \
                       + BASE_INRIX_VOL_PRESIDIO \
                       + EntityEffects",
             data = df)
res_entity = mod_entity.fit(cov_type='clustered', `cluster_entity=True)
```

Failed Attempt 1:

`res_entity.predict(df[['CHAMP_VOL', 'TNC_VOL', 'AVG_DUR_MAJOR_ARTERIALS', 'AVG_DUR_MINOR_ARTERIALS', 'BASE_INRIX_VOL_PRESIDIO']])`

Failed Attempt 2:
```
exog_vars = ['CHAMP_VOL', 'TNC_VOL', 'AVG_DUR_MAJOR_ARTERIALS', 'AVG_DUR_MINOR_ARTERIALS', 'BASE_INRIX_VOL_PRESIDIO']
exog = sm.add_constant(df10[exog_vars])
res_entity.predict(exog)
```

![1](https://user-images.githubusercontent.com/58746879/101547963-f4ff9900-395f-11eb-8edf-d1be9b8a613d.PNG)

I read the documentation of panelOLS.predict(), but I still don't understand how to use the parameters. Please advise!

**Comment by bashtage** [comment]
I can't run enough of the example to make is useful.  Here is a very plain example showing predict.

```python
import numpy as np
import pandas as pd
from linearmodels import PanelOLS

year = np.arange(2010, 2020)
obs_id = np.arange(100)
index = pd.MultiIndex.from_product([obs_id, year], names=["id", "year"])
df = pd.DataFrame(index=index, columns=["y", "x"])
df = df.reset_index()

rg = np.random.default_rng(0)
x = rg.standard_normal(df.shape[0])
e = rg.standard_normal(df.shape[0])
y = x + e + df.id
df["y"] = y
df["x"] = x
df = df.set_index(["id", "year"])
mod = PanelOLS(df.y, df[["x"]], entity_effects=True)
res = mod.fit()
print(res.summary)

in_sample_fit = res.predict(df[["x"]])

new_df = pd.DataFrame(rg.standard_normal((300, 1)))
res.predict(new_df)

```

**Comment by bashtage** [comment]
```
res_entity.predict(df[['CHAMP_VOL', 'TNC_VOL', 'AVG_DUR_MAJOR_ARTERIALS', 'AVG_DUR_MINOR_ARTERIALS', 'BASE_INRIX_VOL_PRESIDIO']])
```

looks like it should work. What error do you see with this?

**Comment by bashtage** [comment]
One thing I notice is the `df` just have a 2-level multiindex or it is reshaped. What does df with this subsampling look like?

**Comment by machenyufitz** [comment]
> ```
> res_entity.predict(df[['CHAMP_VOL', 'TNC_VOL', 'AVG_DUR_MAJOR_ARTERIALS', 'AVG_DUR_MINOR_ARTERIALS', 'BASE_INRIX_VOL_PRESIDIO']])
> ```
> 
> looks like it should work. What error do you see with this?

Hi Kevin, this command does work, and it returns a desired dataframe. However, I want to predict the values for df10 and df16, and also a counterfactual case for df16 with some dummy variables being 0. 

We I try 
`res_entity.predict(df10[['CHAMP_VOL', 'TNC_VOL', 'AVG_DUR_MAJOR_ARTERIALS', 'AVG_DUR_MINOR_ARTERIALS', 'BASE_INRIX_VOL_PRESIDIO']]) ` 

or `res_entity.predict(df16[['CHAMP_VOL', 'TNC_VOL', 'AVG_DUR_MAJOR_ARTERIALS', 'AVG_DUR_MINOR_ARTERIALS', 'BASE_INRIX_VOL_PRESIDIO']])`

A ValueError shows up: 

> ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 1)

**Comment by bashtage** [comment]
Can you show the index of the data frame you are using?

**Comment by machenyufitz** [comment]
> One thing I notice is the `df` just have a 2-level multiindex or it is reshaped. What does df with this subsampling look like?
> 
> I'm pretty sure this is the problem.

I generated df by appending df16 to df10, and set a 2-level multiindex (id, year) to represent each entity. The subsampling df looks like this:

![image](https://user-images.githubusercontent.com/58746879/101819900-b2160080-3ada-11eb-93e2-8b0227535370.png)

**Comment by bashtage** [comment]
What are the indices of `df10` and `df16`?  Are they the same as `df`?  

Also, what do you get when you run

```

from linearmodels.panel.data import PanelData
panel = PanelData(df10[['CHAMP_VOL', 'TNC_VOL', 'AVG_DUR_MAJOR_ARTERIALS', 'AVG_DUR_MINOR_ARTERIALS', 'BASE_INRIX_VOL_PRESIDIO']])
print(panel.shape)
print(panel.dataframe.head())
```

**Comment by machenyufitz** [comment]
Kevin, thank you for your further explanations! I figured out the problem, as my df10 and df16 only have one single index instead of   a multi-index. I really appreciate your time!
