### ISSUE TITLE
R-squared (between) and R-squared (overall) are wrongly estimated

### ISSUE THREAD

**Issue by iankhr** [bashtage/linearmodels#299]
Seems like the package provides weird estimates for R-squared. For example, the R-squared (between) appears to be very close to -1 a lot of times and for different datasets.

To replicate the error please use the dataset and the code provided below. As it can be seen the R-squared (between) appears to be -0.91, although the same estimation in Stata shows between R-squared at the level of 0.0763

The link to the dataset: http://dss.princeton.edu/training/Panel101.dta
The Stata output is available on page 18 of this document: http://www.princeton.edu/~otorres/Panel101.pdf

I attach the code and the data zipped as well, if links do not work: [panelRegression.zip](https://github.com/bashtage/linearmodels/files/5710779/panelRegression.zip)

The code I'm using as follows:
```
from linearmodels import PanelOLS
import pandas as pd

# import data
data = pd.read_stata('Panel101.dta')

# reformating the data
panelData = data.copy()
panelData.set_index(['country', 'year'], inplace = True)
panelData['constant'] = 1

# estimating pooled regression
xLabels = ['constant', 'x1', ]
# define model observe that fixed effects cannot be used here due to dummy variables
model = PanelOLS(panelData['y'], panelData[xLabels], entity_effects = True)
# fit the model
result = model.fit()
print(result)
```

**Comment by bashtage** [comment]
The primary expression for R^2 are different from those in Stata in general. There are correlation-based measures that match Stata. See

https://bashtage.github.io/linearmodels/devel/panel/mathematical-formula.html#r-2-estimates

**Comment by iankhr** [comment]
Alright! Thanks for fast reply! I managed to replicate Stata's between r-squared with the correlation method.

Probably, it's too off topic, but how one should interpret large negative r-squared (between/overall)?

Consider the example above the difference in the estimates (and arguably in interpretation) is big. On one hand, Stata's/correlation-based method produces R-squared of 0.0763, which is low, but still fairly good R-squared given the above model. On the other hand, the weighted residuals method shows -0.91. Does such negative R-squared mean that the model is so severely misspecified that it actually inflates the error terms?

Any tips or references that discuss the issue would be very highly appreciated.

**Comment by bashtage** [comment]
I assume it is the same as when you get any other R^2 that is negative -- this happens when the R2 isn't actually measuring the model you fit, so that the usual constraint that the sum of squared errors is not smaller than the TSS-like term.
