### ISSUE TITLE
No module named 'linearmodels'

### ISSUE THREAD

**Issue by silent0506** [bashtage/linearmodels#302]
I installed and uninstalled the 'linearmodels'  several times.

and I ran the jupyter notebook below code.

`import pandas as pd`
`import numpy as np`
`from statsmodels.api import OLS, add_constant`
`import pandas_datareader.data as web`
`from linearmodels.asset_pricing import LinearFactorModel`
`import matplotlib.pyplot as plt`
`import seaborn as sns` 

and I get these error message

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-13237eb780e7> in <module>()
      5 #import pandas_datareader.data as web
      6 
----> 7 from linearmodels.asset_pricing import LinearFactorModel
      8 
      9 #import matplotlib.pyplot as plt

ImportError: No module named 'linearmodels'
---------------------------------------------------------------------------

how can I fix it?

this is my library of environment. i installed the 'linearmodels'. 
![image](https://user-images.githubusercontent.com/70154806/102763718-69552600-43bd-11eb-8fd5-16557e2fac7b.png)

**Comment by bashtage** [comment]
Your jupyter is probably attached to a different python than the one you used to install linearmodels.

What do you get when you enter

```
where.exe python
```
and
```
where.exe jupyter
```

**Comment by bashtage** [comment]
I'm going to close since there hasn't been any action.  If you still need help, please post here.
