### ISSUE TITLE
ENH: Add support for hypothesis testing using formulas

### ISSUE THREAD

**Issue by blucap** [bashtage/linearmodels#303]
Is there a way to test t-statistics from `PanelOLS` using different reference values?

See this example from [statsmodels](https://www.statsmodels.org/stable/generated/statsmodels.regression.linear_model.OLSResults.t_test.html): 

    from statsmodels.formula.api import ols
    dta = sm.datasets.longley.load_pandas().data
    formula = 'TOTEMP ~ GNPDEFL + GNP + UNEMP + ARMED + POP + YEAR'
    results = ols(formula, dta).fit()
    hypotheses = 'GNPDEFL = GNP, UNEMP = 2, YEAR/1829 = 1'
    t_test = results.t_test(hypotheses)
    print(t_test)

**Comment by bashtage** [comment]
Your hypothesis has multiple restrictions.  You can test this with a Wald test

https://bashtage.github.io/linearmodels/panel/panel/linearmodels.panel.results.PanelResults.wald_test.html#linearmodels.panel.results.PanelResults.wald_test

There is no support for formulas though, so you need to specify your test in the C beta = v format where you define C and v.

**Comment by bashtage** [comment]
This is already available in `wald_test`.
