### ISSUE TITLE
How to interpret the regression result in a standard form?

### ISSUE THREAD

**Issue by nick-zhy** [bashtage/linearmodels#312]
I want to interpret the reg result in a standard form (meet the requirements of academic journals ) like Stata's command `estout` or the command `summary_col` of `statsmodels.iolib.summary2`. 

But I found that `summary_col` can't be applied to the regression result of this package. 

Is there any better method?

**Comment by nick-zhy** [comment]
When apply `summary_col ` to a panel regression result, it reports an error that "'PanelResults' object has no attribute 'bse'"

**Comment by nick-zhy** [comment]
Quickly, I found the solution by myself. See [summary3](https://github.com/YangShuangjie/summary3) by [YangShuangjie]('https://github.com/YangShuangjie').

It works prettey well with the panel result.

**Comment by bashtage** [comment]
Thanks for posting this.
