### ISSUE TITLE
ENH: Add options in fit( ) to specify the optimization method

### ISSUE THREAD

**Issue by GrumpyJun** [bashtage/linearmodels#313]
It was quite often that the LinearFactorModelGMM complains

`Warning: Desired error not necessarily achieved due to precision loss.`

I think this warning comes from the fact that the users cannot specify the method in **scipy.optimize.minimize**, it will go with the default BFGS.

Depending on the property of the objective function, it will be great if one could specify the exact method for the optimization procedure. Here is one example which BGFS just stops at a particular local minimum, and other method may still continue to optimize.

[Example](https://stackoverflow.com/questions/36110998/why-does-scipy-optimize-minimize-default-report-success-without-moving-with-sk)

Maybe linear models are typically fine with BFGS, but it will be better if users could choose the methods. I think this issue also applies to all optimization routines in linearmodels or statsmodels.

**Comment by bashtage** [comment]
I agree the methods that rely on non-linear optimizers should allow the methods used and other options to change.

**Comment by GrumpyJun** [comment]
> I agree the methods that rely on non-linear optimizers should allow the methods used and other options to change.

Maybe also allow the initial guess of the parameters.
