### ISSUE TITLE
exog does not have full rank issue

### ISSUE THREAD

**Issue by OleksiiRomanko** [bashtage/linearmodels#326]
Hi! I am getting the error 'exog does not have full rank issue' when running PanelOls model with the panel data of 117 000 rows, just three regressors. Seems the error is frequent for large datasets. I drille down the issue and it was succesfully resolved for me by modifying def _check_exog_rank in linearmodels/panel/model.py. The issue is that for large datasets, tolerance value for np.linalg.matrix_rank should be adjusted. For example, 
changing line in def _check_exog_rank in linearmodels/panel/model.py 
from rank_of_x = matrix_rank(x)
to rank_of_x = matrix_rank(x,tol=1e-10)
worked for me.

Since for large enough dataset/matrix (in my dataset), nunpy.linalg.matrix_rank calculates matrix rank incorrectly, but specifying better tolerance does solve the issue. Crosschecked matrix rank through several approaches including LU decomposition, so I am pretty sure of the issue.

I propose to include new tolerance parameter (optional) into class PanelOLS initialization, 
and replace 'exog does not have full rank' error message to something like
'exog does not have full rank. Try to adjust tolerance parameter for searching matrix rank and make sure that your explanatory variables are linearly independent'

**Comment by OleksiiRomanko** [comment]
Unfortunately, as the data I am using is proprietary, I am unable to share that to reproduce the issue. However I am sure it will frequently happen in any dataset that is big enough

**Comment by bashtage** [comment]
If you normalize the columns to have unit norm does it work then?  Numerical precision is of course tricky in many cases.

**Comment by bashtage** [comment]
The fundamental question is whether `lstsq` can produce reasonable accuracy when an array is very close to singular.

**Comment by bashtage** [comment]
The effective tolerance does scale with the matrix size.

https://github.com/numpy/numpy/blob/fb215c76967739268de71aa4bda55dd1b062bc2e/numpy/linalg/linalg.py#L1900

**Comment by bashtage** [comment]
Any follow-up on this?  If you make this modification, is the parameter covariance matrix full rank or rank deficient?

**Comment by OleksiiRomanko** [comment]
Hi Kevin!

I think unit normalization would not be the best option since it would lead
to not very user-friendly results (in terms of interpretations of the final
coefficients in the model. If I do a modification, changing the epsilon, I
get a full rank. Basically, as I was saying, the rank was verified using LU
decomposition methods, which seems to produce more 'stable' results than
the default SVD approach in linalg (it should be more computationally
extensive, but it does not rely on any complex algos like inverse matrix).
So I see two quick solutions, either introduce additional parameter and
change error message, or change rank search algorithm (I think it would be
less preferable),

вт, 16 мар. 2021 г. в 19:23, Kevin Sheppard ***@***.***>:

**Comment by bashtage** [comment]
If you take the estimated covariance matrix and do np.linalg.matrix_rank(cov) is it full?

I think adding a tolerance parameter is quite an exotic feature since it is easily to solve by renormalizing the x data if it is just a question of having poorly scaled data. If anything I might implement a keyword that allows the rank check to be skipped in which case all issues fall back to the user to worry about, including numerical instability or reduced rank covariance.

**Comment by bashtage** [comment]
There is a fix in master.  If you feel up to it, could you see if your data can pass now?  I think it effectively has a slightly loser tolerance, and is now implicitly based on a QR decomp.
