### ISSUE TITLE
Standard errors not getting computed correctly for SUR models, Kernel = HAC or robust , method = GLS

### ISSUE THREAD

**Issue by saurabh9a** [bashtage/linearmodels#333]
There seems to an issue with the SUR models with Kernel = HAC or robust , method = GLS. We see that standard errors are not getting computed correctly for the coefficient estimates. 

Test case: 
If we change the scale of the dependent variable by say 10x, the parameter estimates adjust as expected but the standard errors do not show any variation. This is not expected.

Would be of great help if it can be resolved quickly.

**Comment by bashtage** [comment]
Can you give a copy-paste-runnable example?

**Comment by saurabh9a** [comment]
Case #1 and Case #2 both give the same standard errors. Case 2 dependent is 10k times lower than the Case 1

thanks



# Common libraries

import numpy as np
import pandas as pd
import statsmodels.api as sm
from linearmodels.datasets import munnell
from collections import OrderedDict
from linearmodels.system import SUR


data = munnell.load()

regions = {
    "GF": ["AL", "FL", "LA", "MS"],
    "MW": ["IL", "IN", "KY", "MI", "MN", "OH", "WI"],
    "MA": ["DE", "MD", "NJ", "NY", "PA", "VA"],
    "MT": ["CO", "ID", "MT", "ND", "SD", "WY"],
    "NE": ["CT", "ME", "MA", "NH", "RI", "VT"],
    "SO": ["GA", "NC", "SC", "TN", "WV", "AR"],
    "SW": ["AZ", "NV", "NM", "TX", "UT"],
    "CN": ["AK", "IA", "KS", "MO", "NE", "OK"],
    "WC": ["CA", "OR", "WA"],
}


def map_region(state):
    for key in regions:
        if state in regions[key]:
            return key


data["REGION"] = data.ST_ABB.map(map_region)
data["TOTAL_EMP"] = data.groupby(["REGION", "YR"])["EMP"].transform("sum")
data["EMP_SHARE"] = data.EMP / data.TOTAL_EMP
data["WEIGHED_UNEMP"] = data.EMP_SHARE * data.UNEMP


grouped = data.groupby(["REGION", "YR"])
agg_data = grouped[["GSP", "PC", "HWY", "WATER", "UTIL", "EMP", "WEIGHED_UNEMP"]].sum()
for col in ["GSP", "PC", "HWY", "WATER", "UTIL", "EMP"]:
    agg_data["ln" + col] = np.log(agg_data[col])
agg_data["UNEMP"] = agg_data.WEIGHED_UNEMP
agg_data["Intercept"] = 1.0


mod_data = OrderedDict()

# Case 1
for region in ["GF", "SW", "WC", "MT", "NE", "MA", "SO", "MW", "CN"]:
    region_data = agg_data.loc[region]
    dependent = region_data.lnGSP
    exog = region_data[
        ["Intercept", "lnPC", "lnHWY", "lnWATER", "lnUTIL", "lnEMP", "UNEMP"]
    ]
    mod_data[region] = {"dependent": dependent, "exog": exog}
 
mod = SUR(mod_data)   
res1 = mod.fit(cov_type="HAC", method="GLS" )
print(res1)


# Case 2
mod_data = OrderedDict()
for region in ["GF", "SW", "WC", "MT", "NE", "MA", "SO", "MW", "CN"]:
    region_data = agg_data.loc[region]
    dependent = region_data.lnGSP/10000
    exog = region_data[
        ["Intercept", "lnPC", "lnHWY", "lnWATER", "lnUTIL", "lnEMP", "UNEMP"]
    ]
    mod_data[region] = {"dependent": dependent, "exog": exog}

mod = SUR(mod_data)
res2 = mod.fit(cov_type="HAC", method="GLS" )
print(res2)

**Comment by saurabh9a** [comment]
hi Kevin

Is there a chance that this can be resolved soon?

Saurabh

**Comment by bashtage** [comment]
The fix in in #334.  I'll merge when it passes tests.

**Comment by bashtage** [comment]
Now fixed in master.

**Comment by saurabh9a** [comment]
Hi Kevin

Thanks a lot.
Will the changes reflect if I  pip install the package again?

Saurabh

**Comment by bashtage** [comment]
Not until the next release. You can pip install from github

**Comment by bashtage** [comment]
This was been released in linearmodels v4.23 https://pypi.org/project/linearmodels/

**Comment by saurabh9a** [comment]
Thanks a lot, Kevin.
I was also about to check if we have some plans to implement the LR, LM and
Wald test for checking the significance of correlations of residuals across
equations. This is helpful to decide if SUR setup can be useful.

Regards
Saurabh
