### ISSUE TITLE
Clustering input "clusters" Vs "cluster" when passing non entity/time variables

### ISSUE THREAD

**Issue by mavpanos** [bashtage/linearmodels#342]
Hi @bashtage ! Thanks for your work on a great package!

In the last example on "Other clusters" in https://bashtage.github.io/linearmodels/panel/examples/examples.html#Other-clusters it states to use the input "clusters" when clustering on non entity/time variables. I've noticed that using instead the input "cluster" also works, but returns different standard error estimates. I was wondering:

1. should using "cluster" instead of "clusters" be throwing an error?
2. if not, how should the different results be interpreted?

thanks a lot!

**Comment by bashtage** [comment]
Thanks for the report. These were being silently swallowed and ignored, so it was as if you used ClusteredCovariance without clusters, which reduced to robust (White). Fixed in master, and will be fixed in the next release.
