### ISSUE TITLE
LinearFactorModelsResults returns p-values higher than 1

### ISSUE THREAD

**Issue by gusamarante** [bashtage/linearmodels#353]
The class LinearFactorModelsResults computes the p-values for the coefficients but some of them are higher than 1.

Line 122 of linearmodel/results.py currently is:
```python
pvalues = 2 - 2 * stats.norm.cdf(np.abs(tstats))
```

and it should be changed to:
```python
pvalues = 1 - 2 * stats.norm.cdf(np.abs(tstats))
```

**Comment by bashtage** [comment]
For 2 sided p-values it shoudl be 2(1-CDF(|t|)), which looks like what you have shown in the first line.

**Comment by bashtage** [comment]
Table code had a mistake.
