### ISSUE TITLE
Cannot install on Apple Silicon

### ISSUE THREAD

**Issue by QSCTech-Sange** [bashtage/linearmodels#365]

**Comment by bashtage** [comment]
There are no wheels as I don't have an easy way to build them.  This means you have to install from source. What do you see when you try and install?

**Comment by bashtage** [comment]
@QSCTech-Sange I'm trying to build for OSX arm on conda-forge now.  I'll ping back if I succeed.  Until then, you should be able to install using pip.

**Comment by QSCTech-Sange** [comment]
It works!
Thanks a lot!!
