### ISSUE TITLE
Unable to view formula

### ISSUE THREAD

**Issue by akald** [bashtage/linearmodels#367]
When trying to view the formula of a regression, using ```mod.formula``` such as the one in the example below, the code runs but nothing is displayed.

https://stackoverflow.com/questions/69260530/panel-data-regression-with-fixed-effects-using-python

**Comment by bashtage** [comment]
You can only see the formula when you create a model using the formula interface (e.g. `PanelOLS.from_formula`).  If you create it using `DataFrame`s then there is no formula.

**Comment by bashtage** [comment]
Closing as answered but happy to respond further if not clear.
