### ISSUE TITLE
I can not upgrade linearmodels

### ISSUE THREAD

**Issue by mc-zheng** [bashtage/linearmodels#374]
Requirement already satisfied: linearmodels in d:\python\lib\site-packages (4.13)
Collecting linearmodels
  Using cached linearmodels-4.24.tar.gz (1.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scipy>=1.2 in d:\python\lib\site-packages (from linearmodels) (1.5.4)
Requirement already satisfied: patsy in d:\python\lib\site-packages (from linearmodels) (0.5.2)
Requirement already satisfied: numpy>=1.16 in d:\python\lib\site-packages (from linearmodels) (1.19.4)
Requirement already satisfied: pandas>=0.24 in d:\python\lib\site-packages (from linearmodels) (1.1.5)
Collecting property-cached>=1.6.3
  Using cached property_cached-1.6.4-py2.py3-none-any.whl (7.8 kB)
Collecting Cython>=0.29.21
  Using cached Cython-0.29.25-py2.py3-none-any.whl (983 kB)
Requirement already satisfied: mypy-extensions>=0.4 in d:\python\lib\site-packages (from linearmodels) (0.4.3)
Requirement already satisfied: statsmodels>=0.11 in d:\python\lib\site-packages (from linearmodels) (0.12.2)
Collecting pyhdfe>=0.1
  Using cached pyhdfe-0.1.0-py3-none-any.whl (18 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in d:\python\lib\site-packages (from pandas>=0.24->linearmodels) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in d:\python\lib\site-packages (from pandas>=0.24->linearmodels) (2020.5)
Requirement already satisfied: six in d:\python\lib\site-packages (from patsy->linearmodels) (1.15.0)
Building wheels for collected packages: linearmodels
  Building wheel for linearmodels (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\python\python.exe' 'd:\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\z\AppData\Local\Temp\tmp82oe3ym8'
       cwd: C:\Users\z\AppData\Local\Temp\pip-install-m9givxqu\linearmodels_3ae6af1694de46f7abf237baf397f0d9
  Complete output (199 lines):
  [1/1] Cythonizing linearmodels/panel/_utility.pyx
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\linearmodels
  copying linearmodels\conftest.py -> build\lib.win-amd64-3.6\linearmodels
  copying linearmodels\formula.py -> build\lib.win-amd64-3.6\linearmodels
  copying linearmodels\_version.py -> build\lib.win-amd64-3.6\linearmodels
  copying linearmodels\__init__.py -> build\lib.win-amd64-3.6\linearmodels
  creating build\lib.win-amd64-3.6\linearmodels\asset_pricing
  copying linearmodels\asset_pricing\covariance.py -> build\lib.win-amd64-3.6\linearmodels\asset_pricing
  copying linearmodels\asset_pricing\model.py -> build\lib.win-amd64-3.6\linearmodels\asset_pricing
  copying linearmodels\asset_pricing\results.py -> build\lib.win-amd64-3.6\linearmodels\asset_pricing
  copying linearmodels\asset_pricing\__init__.py -> build\lib.win-amd64-3.6\linearmodels\asset_pricing
  creating build\lib.win-amd64-3.6\linearmodels\compat
  copying linearmodels\compat\statsmodels.py -> build\lib.win-amd64-3.6\linearmodels\compat
  copying linearmodels\compat\__init__.py -> build\lib.win-amd64-3.6\linearmodels\compat
  creating build\lib.win-amd64-3.6\linearmodels\datasets
  copying linearmodels\datasets\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets
  creating build\lib.win-amd64-3.6\linearmodels\iv
  copying linearmodels\iv\absorbing.py -> build\lib.win-amd64-3.6\linearmodels\iv
  copying linearmodels\iv\common.py -> build\lib.win-amd64-3.6\linearmodels\iv
  copying linearmodels\iv\covariance.py -> build\lib.win-amd64-3.6\linearmodels\iv
  copying linearmodels\iv\data.py -> build\lib.win-amd64-3.6\linearmodels\iv
  copying linearmodels\iv\gmm.py -> build\lib.win-amd64-3.6\linearmodels\iv
  copying linearmodels\iv\model.py -> build\lib.win-amd64-3.6\linearmodels\iv
  copying linearmodels\iv\results.py -> build\lib.win-amd64-3.6\linearmodels\iv
  copying linearmodels\iv\_utility.py -> build\lib.win-amd64-3.6\linearmodels\iv
  copying linearmodels\iv\__init__.py -> build\lib.win-amd64-3.6\linearmodels\iv
  creating build\lib.win-amd64-3.6\linearmodels\panel
  copying linearmodels\panel\covariance.py -> build\lib.win-amd64-3.6\linearmodels\panel
  copying linearmodels\panel\data.py -> build\lib.win-amd64-3.6\linearmodels\panel
  copying linearmodels\panel\model.py -> build\lib.win-amd64-3.6\linearmodels\panel
  copying linearmodels\panel\results.py -> build\lib.win-amd64-3.6\linearmodels\panel
  copying linearmodels\panel\utility.py -> build\lib.win-amd64-3.6\linearmodels\panel
  copying linearmodels\panel\__init__.py -> build\lib.win-amd64-3.6\linearmodels\panel
  creating build\lib.win-amd64-3.6\linearmodels\shared
  copying linearmodels\shared\base.py -> build\lib.win-amd64-3.6\linearmodels\shared
  copying linearmodels\shared\covariance.py -> build\lib.win-amd64-3.6\linearmodels\shared
  copying linearmodels\shared\exceptions.py -> build\lib.win-amd64-3.6\linearmodels\shared
  copying linearmodels\shared\hypotheses.py -> build\lib.win-amd64-3.6\linearmodels\shared
  copying linearmodels\shared\io.py -> build\lib.win-amd64-3.6\linearmodels\shared
  copying linearmodels\shared\linalg.py -> build\lib.win-amd64-3.6\linearmodels\shared
  copying linearmodels\shared\typed_getters.py -> build\lib.win-amd64-3.6\linearmodels\shared
  copying linearmodels\shared\utility.py -> build\lib.win-amd64-3.6\linearmodels\shared
  copying linearmodels\shared\__init__.py -> build\lib.win-amd64-3.6\linearmodels\shared
  creating build\lib.win-amd64-3.6\linearmodels\system
  copying linearmodels\system\covariance.py -> build\lib.win-amd64-3.6\linearmodels\system
  copying linearmodels\system\gmm.py -> build\lib.win-amd64-3.6\linearmodels\system
  copying linearmodels\system\model.py -> build\lib.win-amd64-3.6\linearmodels\system
  copying linearmodels\system\results.py -> build\lib.win-amd64-3.6\linearmodels\system
  copying linearmodels\system\_utility.py -> build\lib.win-amd64-3.6\linearmodels\system
  copying linearmodels\system\__init__.py -> build\lib.win-amd64-3.6\linearmodels\system
  creating build\lib.win-amd64-3.6\linearmodels\tests
  copying linearmodels\tests\test_examples.py -> build\lib.win-amd64-3.6\linearmodels\tests
  copying linearmodels\tests\test_tester.py -> build\lib.win-amd64-3.6\linearmodels\tests
  copying linearmodels\tests\__init__.py -> build\lib.win-amd64-3.6\linearmodels\tests
  creating build\lib.win-amd64-3.6\linearmodels\typing
  copying linearmodels\typing\data.py -> build\lib.win-amd64-3.6\linearmodels\typing
  copying linearmodels\typing\iv.py -> build\lib.win-amd64-3.6\linearmodels\typing
  copying linearmodels\typing\__init__.py -> build\lib.win-amd64-3.6\linearmodels\typing
  creating build\lib.win-amd64-3.6\linearmodels\datasets\birthweight
  copying linearmodels\datasets\birthweight\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets\birthweight
  creating build\lib.win-amd64-3.6\linearmodels\datasets\card
  copying linearmodels\datasets\card\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets\card
  creating build\lib.win-amd64-3.6\linearmodels\datasets\fertility
  copying linearmodels\datasets\fertility\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets\fertility
  creating build\lib.win-amd64-3.6\linearmodels\datasets\french
  copying linearmodels\datasets\french\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets\french
  creating build\lib.win-amd64-3.6\linearmodels\datasets\fringe
  copying linearmodels\datasets\fringe\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets\fringe
  creating build\lib.win-amd64-3.6\linearmodels\datasets\jobtraining
  copying linearmodels\datasets\jobtraining\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets\jobtraining
  creating build\lib.win-amd64-3.6\linearmodels\datasets\meps
  copying linearmodels\datasets\meps\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets\meps
  creating build\lib.win-amd64-3.6\linearmodels\datasets\mroz
  copying linearmodels\datasets\mroz\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets\mroz
  creating build\lib.win-amd64-3.6\linearmodels\datasets\munnell
  copying linearmodels\datasets\munnell\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets\munnell
  creating build\lib.win-amd64-3.6\linearmodels\datasets\wage
  copying linearmodels\datasets\wage\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets\wage
  creating build\lib.win-amd64-3.6\linearmodels\datasets\wage_panel
  copying linearmodels\datasets\wage_panel\__init__.py -> build\lib.win-amd64-3.6\linearmodels\datasets\wage_panel
  creating build\lib.win-amd64-3.6\linearmodels\tests\asset_pricing
  copying linearmodels\tests\asset_pricing\test_covariance.py -> build\lib.win-amd64-3.6\linearmodels\tests\asset_pricing
  copying linearmodels\tests\asset_pricing\test_formulas.py -> build\lib.win-amd64-3.6\linearmodels\tests\asset_pricing
  copying linearmodels\tests\asset_pricing\test_linear_factor_gmm.py -> build\lib.win-amd64-3.6\linearmodels\tests\asset_pricing
  copying linearmodels\tests\asset_pricing\test_linear_factor_model.py -> build\lib.win-amd64-3.6\linearmodels\tests\asset_pricing
  copying linearmodels\tests\asset_pricing\test_model.py -> build\lib.win-amd64-3.6\linearmodels\tests\asset_pricing
  copying linearmodels\tests\asset_pricing\_utility.py -> build\lib.win-amd64-3.6\linearmodels\tests\asset_pricing
  copying linearmodels\tests\asset_pricing\__init__.py -> build\lib.win-amd64-3.6\linearmodels\tests\asset_pricing
  creating build\lib.win-amd64-3.6\linearmodels\tests\datasets
  copying linearmodels\tests\datasets\test_datasets.py -> build\lib.win-amd64-3.6\linearmodels\tests\datasets
  copying linearmodels\tests\datasets\__init__.py -> build\lib.win-amd64-3.6\linearmodels\tests\datasets
  creating build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\test_absorbing.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\test_against_stata.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\test_covariance.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\test_data.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\test_formulas.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\test_gmm.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\test_missing_data.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\test_model.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\test_postestimation.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\test_results.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\_utility.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  copying linearmodels\tests\iv\__init__.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv
  creating build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_between_ols.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_cluster_input_formats.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_data.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_fama_macbeth.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_firstdifference_ols.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_formula.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_model.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_panel_covariance.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_panel_ols.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_pooled_ols.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_random_effects.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_results.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_simulated_against_stata.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\test_utility.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\_utility.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  copying linearmodels\tests\panel\__init__.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel
  creating build\lib.win-amd64-3.6\linearmodels\tests\shared
  copying linearmodels\tests\shared\test_base.py -> build\lib.win-amd64-3.6\linearmodels\tests\shared
  copying linearmodels\tests\shared\test_typed_getters.py -> build\lib.win-amd64-3.6\linearmodels\tests\shared
  copying linearmodels\tests\shared\test_utility.py -> build\lib.win-amd64-3.6\linearmodels\tests\shared
  copying linearmodels\tests\shared\__init__.py -> build\lib.win-amd64-3.6\linearmodels\tests\shared
  creating build\lib.win-amd64-3.6\linearmodels\tests\system
  copying linearmodels\tests\system\test_3sls.py -> build\lib.win-amd64-3.6\linearmodels\tests\system
  copying linearmodels\tests\system\test_3sls_against_stata.py -> build\lib.win-amd64-3.6\linearmodels\tests\system
  copying linearmodels\tests\system\test_covariance.py -> build\lib.win-amd64-3.6\linearmodels\tests\system
  copying linearmodels\tests\system\test_equivalence.py -> build\lib.win-amd64-3.6\linearmodels\tests\system
  copying linearmodels\tests\system\test_formulas.py -> build\lib.win-amd64-3.6\linearmodels\tests\system
  copying linearmodels\tests\system\test_gmm.py -> build\lib.win-amd64-3.6\linearmodels\tests\system
  copying linearmodels\tests\system\test_sur.py -> build\lib.win-amd64-3.6\linearmodels\tests\system
  copying linearmodels\tests\system\test_sur_against_stata.py -> build\lib.win-amd64-3.6\linearmodels\tests\system
  copying linearmodels\tests\system\test_utility.py -> build\lib.win-amd64-3.6\linearmodels\tests\system
  copying linearmodels\tests\system\_utility.py -> build\lib.win-amd64-3.6\linearmodels\tests\system
  copying linearmodels\tests\system\__init__.py -> build\lib.win-amd64-3.6\linearmodels\tests\system
  creating build\lib.win-amd64-3.6\linearmodels\tests\iv\results
  copying linearmodels\tests\iv\results\execute-stata-simulated-data.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv\results
  copying linearmodels\tests\iv\results\execute-stata.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv\results
  copying linearmodels\tests\iv\results\read_stata_results.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv\results
  copying linearmodels\tests\iv\results\simulated-test-data.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv\results
  copying linearmodels\tests\iv\results\__init__.py -> build\lib.win-amd64-3.6\linearmodels\tests\iv\results
  creating build\lib.win-amd64-3.6\linearmodels\tests\panel\results
  copying linearmodels\tests\panel\results\execute-stata-simulated-data.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel\results
  copying linearmodels\tests\panel\results\generate-panel-data.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel\results
  copying linearmodels\tests\panel\results\parse_stata_results.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel\results
  copying linearmodels\tests\panel\results\__init__.py -> build\lib.win-amd64-3.6\linearmodels\tests\panel\results
  creating build\lib.win-amd64-3.6\linearmodels\tests\system\results
  copying linearmodels\tests\system\results\execute-stata-3sls.py -> build\lib.win-amd64-3.6\linearmodels\tests\system\results
  copying linearmodels\tests\system\results\execute-stata.py -> build\lib.win-amd64-3.6\linearmodels\tests\system\results
  copying linearmodels\tests\system\results\generate_data.py -> build\lib.win-amd64-3.6\linearmodels\tests\system\results
  copying linearmodels\tests\system\results\parse_stata_3sls_results.py -> build\lib.win-amd64-3.6\linearmodels\tests\system\results
  copying linearmodels\tests\system\results\parse_stata_results.py -> build\lib.win-amd64-3.6\linearmodels\tests\system\results
  copying linearmodels\tests\system\results\__init__.py -> build\lib.win-amd64-3.6\linearmodels\tests\system\results
  running egg_info
  writing linearmodels.egg-info\PKG-INFO
  writing dependency_links to linearmodels.egg-info\dependency_links.txt
  writing requirements to linearmodels.egg-info\requires.txt
  writing top-level names to linearmodels.egg-info\top_level.txt
  reading manifest file 'linearmodels.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  adding license file 'LICENSE.md'
  writing manifest file 'linearmodels.egg-info\SOURCES.txt'
  copying linearmodels\panel\_utility.c -> build\lib.win-amd64-3.6\linearmodels\panel
  copying linearmodels\datasets\birthweight\birthweight.csv.bz2 -> build\lib.win-amd64-3.6\linearmodels\datasets\birthweight
  copying linearmodels\datasets\card\card.csv.bz2 -> build\lib.win-amd64-3.6\linearmodels\datasets\card
  copying linearmodels\datasets\fertility\fertility.csv.bz2 -> build\lib.win-amd64-3.6\linearmodels\datasets\fertility
  copying linearmodels\datasets\french\french.csv.bz2 -> build\lib.win-amd64-3.6\linearmodels\datasets\french
  copying linearmodels\datasets\fringe\fringe.csv.bz2 -> build\lib.win-amd64-3.6\linearmodels\datasets\fringe
  copying linearmodels\datasets\jobtraining\jobtraining.csv.bz2 -> build\lib.win-amd64-3.6\linearmodels\datasets\jobtraining
  copying linearmodels\datasets\meps\meps.csv.bz2 -> build\lib.win-amd64-3.6\linearmodels\datasets\meps
  copying linearmodels\datasets\mroz\mroz.csv.bz2 -> build\lib.win-amd64-3.6\linearmodels\datasets\mroz
  copying linearmodels\datasets\munnell\munnell.csv.bz2 -> build\lib.win-amd64-3.6\linearmodels\datasets\munnell
  copying linearmodels\datasets\wage\wage.csv.bz2 -> build\lib.win-amd64-3.6\linearmodels\datasets\wage
  copying linearmodels\datasets\wage_panel\wage_panel.csv.bz2 -> build\lib.win-amd64-3.6\linearmodels\datasets\wage_panel
  copying linearmodels\tests\iv\results\housing.csv -> build\lib.win-amd64-3.6\linearmodels\tests\iv\results
  copying linearmodels\tests\iv\results\simulated-data.dta -> build\lib.win-amd64-3.6\linearmodels\tests\iv\results
  copying linearmodels\tests\iv\results\stata-iv-housing-results.txt -> build\lib.win-amd64-3.6\linearmodels\tests\iv\results
  copying linearmodels\tests\iv\results\stata-iv-simulated-results.txt -> build\lib.win-amd64-3.6\linearmodels\tests\iv\results
  copying linearmodels\tests\panel\results\simulated-panel.dta -> build\lib.win-amd64-3.6\linearmodels\tests\panel\results
  copying linearmodels\tests\panel\results\stata-panel-simulated-results.txt -> build\lib.win-amd64-3.6\linearmodels\tests\panel\results
  copying linearmodels\tests\system\results\simulated-3sls.dta -> build\lib.win-amd64-3.6\linearmodels\tests\system\results
  copying linearmodels\tests\system\results\simulated-sur.dta -> build\lib.win-amd64-3.6\linearmodels\tests\system\results
  copying linearmodels\tests\system\results\stata-3sls-results.txt -> build\lib.win-amd64-3.6\linearmodels\tests\system\results
  copying linearmodels\tests\system\results\stata-sur-results.txt -> build\lib.win-amd64-3.6\linearmodels\tests\system\results
  copying linearmodels\panel\_utility.pyx -> build\lib.win-amd64-3.6\linearmodels\panel
  UPDATING build\lib.win-amd64-3.6\linearmodels/_version.py
  set build\lib.win-amd64-3.6\linearmodels/_version.py to '4.24'
  running build_ext
  building 'linearmodels.panel._utility' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for linearmodels
Failed to build linearmodels
ERROR: Could not build wheels for linearmodels, which is required to install pyproject.toml-based projects

**Comment by bashtage** [comment]
Your python is too old to get the latest version.  You should upgrade to Python 3.7 or newer if you want to use prebuilt binaries.  Alternatively, you can install the build tools as indicated in that link and build yourself.
