### ISSUE TITLE
Add absorbing regression for GLM

### ISSUE THREAD

**Issue by aeturrell** [bashtage/linearmodels#394]
Apologies if this is totally out of scope.

As far as I can tell, there's no mature, cross-OS, maintained Python package for absorbing regression for generalized linear models. There's a prototype version using jax + GPUs in [fastreg](https://github.com/iamlemec/fastreg) but I haven't seen anything else, and it's not available in statsmodels. Definitely of secondary importance, but it would be great to have it available via a formula API too.

It would be fab to have this feature!

**Comment by bashtage** [comment]
Hi @aeturrell, GLM is out of scope for their project.  I think the natural home would be statsmodels, given the extensive GLM capabilities there.
