### ISSUE TITLE
Breakages in the Formulaic API

### ISSUE THREAD

**Issue by matthewwardrop** [bashtage/linearmodels#412]
Hi @bashtage ,

Apologies... I only just noticed you had merged support for Formulaic, but didn't add the recommended bounding on the version due to the unstable nature of the API (e.g. `formulaic >=0.2,<0.3`). In Formulaic [0.3.x](https://github.com/matthewwardrop/formulaic/releases/tag/v0.3.0), the API was updated to add support for structured formulae, in a way that likely breaks your implementation.

In particular, `Formula("y~x").terms` is no longer a tuple; it is a `Structured` instance with attributes of `rhs` and `lhs`. In the future this will allow us to add support mixed models, two-stage models, and so on; exposing each term-set as a child in some tree-structure. However, in the short term... I think I've broken you.

Sorry! Let me know if you need help porting your code, or if the new API sucks in ways I didn't anticipate.

**Comment by bashtage** [comment]
I should have been more strict.  Fix wasn't too bad.

**Comment by bashtage** [comment]
Only mild issue was updating terms in a formula.  I sometimes need to remove terms that I handle directly and this seemed to need me to create a new `Structured` and then assign this to terms. The terms in a `Structured` are lists but don't seem to be easy to directly modify.

**Comment by matthewwardrop** [comment]
Roger that. The lists themselves are mutable, but direct assignment into the `Structured` instance was not implemented. I had been thinking to do that anyway, but this observation clinches it... I'll add this by version 0.4, likely in an upcoming 0.3 release soon.
