### ISSUE TITLE
linearmodels first difference works in version 4.24 on Linux laptop, fails in version 4.25 on Windows laptop

### ISSUE THREAD

**Issue by kflamm** [bashtage/linearmodels#422]
When I install using 'pip install' on my Linux laptop, I get version 4.24. When I do the same on my Windows laptop, I get versiion 4.25 When I run the attached notebook on my Linux laptop, it runs. When I run the same notebook on my Windows laptop, it fails and gives me an opaque error message. Any clues as to what is going on? Have I stumbled across a bug?

Thanks,
Ken Flamm
[linearmodels_glitch.zip](https://github.com/bashtage/linearmodels/files/8344609/linearmodels_glitch.zip)

**Comment by kflamm** [comment]
It's definitely a bug in 4.25, on windows hardware at least. I uninstalled linearmodels, then reinstalled 4.24 and the notebook runs fine on my Windows laptop. Let me know if I can be helpful.

Regards,
Ken Flamm

**Comment by bashtage** [comment]
It is formulaic. You need to `pip install formulaic<0.3` to get LM 4.25 to work.  I need to release a new version which requires formulaic 0.3.x and won't have this issue.
