### ISSUE TITLE
Get error when using result.time_info.min() for PanelOLS

### ISSUE THREAD

**Issue by Paq70** [bashtage/linearmodels#461]
Dear developers,

I get a wrong info when using result.time_info.min() for PanelOLS. It actually shows the same result as result.time_info.total, which doesn't mean any sense. Can somebody fix it?

**Comment by bashtage** [comment]
@Paq70 because `time_info` is a `Series`, you can't use dot notation to access `min`.  So don't use `result.time_info.min`, instead use `result.time_info["min"]`.

**Comment by bashtage** [comment]
Closing as answered, but please continue to post if this isn't enough to fix your issue.

**Comment by Paq70** [comment]
Solved, thank you much @bashtage !!!
