### ISSUE TITLE
Link to  bashtage.github.io/linearmodels/doc not working

### ISSUE THREAD

**Issue by blucap** [bashtage/linearmodels#462]
On the main GitHub page, the link to the docs under `About` is not working:

[bashtage.github.io/linearmodels/doc](https://bashtage.github.io/linearmodels/doc)

**Comment by bashtage** [comment]
@blucap Thanks for the report.  Where are you seeing this broken link?  I can't seem to find it easily in the source.

**Comment by bashtage** [comment]
Sorry, should have read your issue more carefully. Fixed.
