### ISSUE TITLE
Documentation clarification on predict() results

### ISSUE THREAD

**Issue by cearlefraym** [bashtage/linearmodels#465]
full q here: https://stackoverflow.com/questions/72969440/interpreting-results-from-linearmodels-panelols-predict-method

For `PanelOLS` with `entity_effects=True` (should be equivalent to fixed effects), does `predict()` return a prediction of the expected y_it - yi bar, or actual predictions of yit?

**Comment by bashtage** [comment]
The model is always Y=XB + epsilon + (eta_t <Time Effect>) + (nu_i <Entity Effect>).  The effects are treated as errors, and so when you predict you get `new_x @ params` and so the entity effects are not used.

**Comment by cearlefraym** [comment]
Thanks for the quick response and clarification, @bashtage. Given that the model uses `new_x @ params`, would first time-demeaning `new_x` before passing to `predict` achieve a y_it - yi bar prediction? I.e. could predictions on new, time-demeaned data be interpreted as expected changes in y_it from their time-averaged y_it (yi bar). Thanks again!

**Comment by bashtage** [comment]
Yes. If you demended using the average of the y's for the entity included in the model, and similarly for the x's included in the model, than you would get what you are after.

**Comment by cearlefraym** [comment]
Thanks again, that fully clarifies my question -- I'll close this issue.

**Comment by bashtage** [comment]
You are welcome.
