### ISSUE TITLE
Add options to operate comparison table  #feature

### ISSUE THREAD

**Issue by PeikaiLi** [bashtage/linearmodels#498]
like the summary_col
```
from statsmodels.iolib.summary2 import summary_col
```
OR
stargazer
```
https://github.com/mwburke/stargazer
```

**Comment by PeikaiLi** [comment]
Buy the way, they are like to do it too
https://github.com/mwburke/stargazer/issues/26

**Comment by bashtage** [comment]
This is already implemented for both panel models and iv models.

https://bashtage.github.io/linearmodels/panel/panel/linearmodels.panel.results.compare.html
https://bashtage.github.io/linearmodels/iv/iv/linearmodels.iv.results.compare.html
