### ISSUE TITLE
ENH: Add average adjusted R2 in FamaMacBeth

### ISSUE THREAD

**Issue by nick-zhy** [bashtage/linearmodels#499]
Currently the FamaMacBeth can output overall r2, within r2, but no average r2 which is frequently used in empirical asset pricing studies. Is it possible to add this output of the function?

The average adj. r2 should be the time series average of adjusted r2 at each time inverval.

**Comment by nick-zhy** [comment]
> Do you mean the simple average of the time series adjusted R-squared?

Exactly. It is quite common in empirical asset pricing to report the average adj. R2 in their Fama-Macbeth regressions.

It is just calculated as the average of adj. R2 at each time point.

**Comment by bashtage** [comment]
Ok, it should be easy to add.

**Comment by FuHuakang** [comment]
Has the average R² been included? I don't seem to see it in the summary.
