### ISSUE TITLE
Variables order in results

### ISSUE THREAD

**Issue by DongGilKim** [bashtage/linearmodels#501]
Hi Kevin, 

Thank you for developing an amazing package. Thanks to you, many Python users are able to do decent statistical analyses that are not covered by the statsmodel. 

I have one suggestion for your package. When I run linearmodels, By default, the package orders the independent variables alphabetically, which differs from statsmodel. It would be much more convenient if the package orders the variables as the user specified in the formula as in the statsmodel. Because the variables are currently alphabetically in linearmodels, it is inconvenient and confusing to loop over and get the specific parameters and statistics to display.

Best,
Dong Gil Kim

**Comment by bashtage** [comment]
Can your provide me with an example where this happens?

**Comment by bashtage** [comment]
The reordering is done in formulaic.  I've asked for an enhancement that would preserve the order.

xref matthewwardrop/formulaic#135

**Comment by DongGilKim** [comment]
I see, it was coming from a formulaic package. I also added comments to Matthew who developed the formulaic package. Thanks for the answer and support, Kevin.

**Comment by bashtage** [comment]
I'll make this available once it is exposed in formulaic.

**Comment by bashtage** [comment]
This will come when formulaic releases its next version, which I think will be 1.0.

**Comment by matthewwardrop** [comment]
@bashtage I've released the next version as 0.6.0, there's enough important fixes and extensions that I wanted to release, but still not quite there on the documentation and typing/linting front. You can treat 0.6.0 as something akin to an early 1.0.0 preview. Let me know if you find anything!

**Comment by bashtage** [comment]
This is implemented in #521.

**Comment by bashtage** [comment]
#521 has been merged.  Thanks.
