### ISSUE TITLE
Min. obs pr Entities/Time Periods is sometimes reported as 0

### ISSUE THREAD

**Issue by eirki** [bashtage/linearmodels#534]
The way `panel_structure_stats` is implemented means that it will sometimes claim that the minimum observations pr entity is 0. Example:

```python
import pandas as pd
import linearmodels
df = pd.DataFrame(
    {
        "a": [432, 543, 367, 765, 23, 76, 654, 87],
        "b": [876, 864, 345, 531, 457, 876, 345, 213],
        "i1": [1, 2, 1, 3, 1, 3, 1, 3],
        "i2": [1000, 1000, 2000, 2000, 3000, 3000, 4000, 4000],
    },
).set_index(["i1", "i2"])
df = df.drop(2, level="i1")
mod = linearmodels.PanelOLS.from_formula("a ~ b", df)
mod._info()[0]
```

Result:
```
mean      2.333333
median    3.000000
max       4.000000
min       0.000000  <-------
total     3.000000
Name: Observations per entity, dtype: float64
```

The reason this happens is that the groups are calculated using `numpy.bincount` of `entity_ids` https://github.com/bashtage/linearmodels/blob/6ec8547b11fce465fda5a85ac44ccd717510cc62/linearmodels/panel/model.py#L93 and `entity_ids` are defined using the `.codes` of that index https://github.com/bashtage/linearmodels/blob/6ec8547b11fce465fda5a85ac44ccd717510cc62/linearmodels/panel/data.py#L371

Since the index (`"i1"`) included the value `2` on creation, but that value was since dropped, the `.codes` of that index now looks like this: `array([0, 0, 2, 0, 2, 0, 2], dtype=int8)`. Numpy's bincount will helpfully tell us that we have 0 cases of the value 1:

```python
np.bincount(df.index.codes[0])
>>> array([4, 0, 3])
```

This 0 is then reported as the minimum number of observations pr entity.

**Comment by bashtage** [comment]
Thanks.   Looks like an easy fix.

**Comment by bashtage** [comment]
It is out now.
