### ISSUE TITLE
Small sample correction clustered avaialble?

### ISSUE THREAD

**Issue by joonro** [bashtage/linearmodels#537]
Hi, thanks for the great package that is easy-to-use. 

I was trying both `statsmodels` and `linearmodels.PanelOLS` to estimate the same fixed effects model, to make sure I get the same results. I found that when I use clustered standard errors, linearmodels was producing smaller standard errors for the same model. 

It seems the issue is that in statsmodels, `use_correction` option was used, which provides small sample correction. When I turn that option to `False`, I get very similar standard errors from both packages.

I looked at the documentation but couldn't find any mention of applying the small sample correction for linearmodels when clustered standard errors, I was wondering if this is not available?

**Comment by spring-haru** [comment]
Adding `group_debias=True` to `.fit()` may help, as reported in #540.

**Comment by bashtage** [comment]
Please see #540.  Closing as a duplicate.
