### ISSUE TITLE
Link on top of your github page has extra s

### ISSUE THREAD

**Issue by thequackdaddy** [bashtage/linearmodels#58]
Hello,

This looks interesting. 

The link on the top of https://github.com/bashtage/linearmodels points to 

https://bashtage.github.io/linearmodels/docs

I think there is an extra "s" in "docs"

<img width="647" alt="screen shot 2017-04-19 at 9 39 57 pm" src="https://cloud.githubusercontent.com/assets/8186432/25211070/d405edd2-2548-11e7-9dba-f828db783b44.png">

**Comment by bashtage** [comment]
Thanks - I changed it to `doc` at some point and missed that one.
