### ISSUE TITLE
Typos in the documentation (Instrumental Variable Estimation, Formulas and Mathematical Detail)

### ISSUE THREAD

**Issue by gregor-schueler** [bashtage/linearmodels#616]
> The model can be expressed compactly
> ```math
> \begin{aligned}
> Y & =X_1 \beta_1+X_2 \beta_1+\epsilon=X \beta+\epsilon \\
> X_2 & =Z_1 \gamma_1+Z_2 \gamma_2+u=Z \gamma+u
> \end{aligned}
> ```
in the first equation the second $\beta_1$ should be $\beta_2$ and in the text right below an "if" should be an "of"

> [...] $X$ is the $n$ by $k$ matrix **~~if~~ of** regressors where row $i$ of $X$ is $x_i^{\prime}$.  [...]

**Comment by bashtage** [comment]
Thanks.
