### ISSUE TITLE
Using scipy's genetic algorithm for initial parameter estimation

### ISSUE THREAD

**Issue by zunzun** [bashtage/linearmodels#93]
I have used scipy's Differential Evolution genetic algorithm to find initial parameters for fitting a double Lorentzian peak equation to Raman spectroscopy data. I found that the results were excellent, and see from your GitHub project that you might find my project to be interesting.

The GitHub project, with a test spectroscopy data file, is:

https://github.com/zunzun/RamanSpectroscopyFit

If you have any questions, please let me know.

James Phillips

**Comment by bashtage** [comment]
I don't think is is really an issue for linearmodels, so I'm going to close.

**Comment by zunzun** [comment]
OK.
