### ISSUE TITLE
Inconsistent Results of Fixed Effects (PanelOLS)

### ISSUE THREAD

**Issue by ma-ji** [bashtage/linearmodels#99]
First of all, very much appreciate this great package for panel data analysis in Python!

I'm doing panel regression with fixed effects of entity and time. By using the same dataset and running through R, Python Statsmodels, and Python linearmodels (this package), the results of R and Statsmodels (using dummies) are consistent, but they both differ from linearmodels (PanelOLS, I've tried unadjusted, robust, etc.). Why?

I'm a beginner of econometrics, guess you may need more information about the analysis (or maybe I get wrong!). Or we may experiment on a public dataset. Let me know how we can help to improve the robustness of this package. Thanks!

**Comment by bashtage** [comment]
A public dataset or better a simulated dataset would be preferred.  In the
meantime, could you post the command you are running?

**Comment by ma-ji** [comment]
```Python
# Test module robustness.
from linearmodels.datasets import jobtraining
df_jobtrain=jobtraining.load()[['year', 'fcode', 'employ', 'tothrs']].set_index(['fcode', 'year']).dropna()
PanelOLS.from_formula('tothrs ~ 1+employ+EntityEffects+TimeEffects', df_jobtrain).fit(cov_type='unadjusted')
# Export dataset for R.
df_jobtrain.to_csv('../../dataset/jobtraining_part.tsv', sep='\t')
```
The above codes give the following results:
> F-test for Poolability: 13.704
> P-value: 0.0000
> Distribution: F(136,252)

```R
### Test module robustness.
attach(jobtraining_part)
dum_year=as.factor(year)
dum_fcode=as.factor(fcode)
summary(lm(formula = tothrs~employ+dum_year+dum_fcode))
```
The above codes give the following results:
> F-statistic: 13.93 on 137 and 252 DF,  p-value: < 2.2e-16

The results are slightly different. Maybe I'm not coding in the right way?

**Comment by bashtage** [comment]
I don't fully understand the R degrees of freedom, There are 390 obs, and there are 2 regressors (a constant and employ), and so there should be 2 used.  The R DOFs add up to 137+252 = 389 which seems to be 1 too many. I suspect that the test you are using from R is testing that the constant is also 0, which my test does not do.

**Comment by bashtage** [comment]
Have you tried running the model in the panel package for R?  Sometimes there are adjustments required for LSDV to work as expected, especially when there is a constant in the model.

**Comment by bashtage** [comment]
I believe my code is testing the right thing and the R code is testing a different hypothesis (in particular R is including the intercept, or equivalent).  I'm going to close this.
